-- Game Night ZA global word banks.
-- Common-word source: google-10000-english (filtered for game suitability),
-- Password nouns cross-checked against an English noun list, and spelling
-- normalised toward British/South African usage where applicable.

WITH seed(prompt, category) AS (VALUES
  ('november', 'Medium'),
  ('market', 'Easy'),
  ('library', 'Medium'),
  ('really', 'Easy'),
  ('action', 'Easy'),
  ('start', 'Easy'),
  ('series', 'Easy'),
  ('model', 'Easy'),
  ('features', 'Medium'),
  ('industry', 'Medium'),
  ('plan', 'Easy'),
  ('human', 'Easy'),
  ('provided', 'Medium'),
  ('required', 'Medium'),
  ('second', 'Easy'),
  ('accessories', 'Hard'),
  ('cost', 'Easy'),
  ('movie', 'Easy'),
  ('forums', 'Easy'),
  ('march', 'Easy'),
  ('september', 'Medium'),
  ('better', 'Easy'),
  ('questions', 'Medium'),
  ('july', 'Easy'),
  ('going', 'Easy'),
  ('medical', 'Medium'),
  ('test', 'Easy'),
  ('friend', 'Easy'),
  ('come', 'Easy'),
  ('server', 'Easy'),
  ('study', 'Easy'),
  ('application', 'Hard'),
  ('cart', 'Easy'),
  ('staff', 'Easy'),
  ('articles', 'Medium'),
  ('feedback', 'Medium'),
  ('again', 'Easy'),
  ('play', 'Easy'),
  ('looking', 'Medium'),
  ('issues', 'Easy'),
  ('april', 'Easy'),
  ('never', 'Easy'),
  ('users', 'Easy'),
  ('complete', 'Medium'),
  ('street', 'Easy'),
  ('topic', 'Easy'),
  ('comment', 'Medium'),
  ('financial', 'Medium'),
  ('things', 'Easy'),
  ('working', 'Medium'),
  ('against', 'Medium'),
  ('standard', 'Medium'),
  ('person', 'Easy'),
  ('below', 'Easy'),
  ('mobile', 'Easy'),
  ('less', 'Easy'),
  ('blog', 'Easy'),
  ('party', 'Easy'),
  ('payment', 'Medium'),
  ('equipment', 'Medium'),
  ('login', 'Easy'),
  ('student', 'Medium'),
  ('programs', 'Medium'),
  ('offers', 'Easy'),
  ('legal', 'Easy'),
  ('above', 'Easy'),
  ('recent', 'Easy'),
  ('park', 'Easy'),
  ('stores', 'Easy'),
  ('side', 'Easy'),
  ('problem', 'Medium'),
  ('give', 'Easy'),
  ('memory', 'Easy'),
  ('performance', 'Hard'),
  ('social', 'Easy'),
  ('august', 'Easy'),
  ('quote', 'Easy'),
  ('language', 'Medium'),
  ('story', 'Easy'),
  ('sell', 'Easy'),
  ('options', 'Medium'),
  ('experience', 'Hard'),
  ('rates', 'Easy'),
  ('create', 'Easy'),
  ('body', 'Easy'),
  ('young', 'Easy'),
  ('america', 'Medium'),
  ('important', 'Medium'),
  ('field', 'Easy'),
  ('east', 'Easy'),
  ('paper', 'Easy'),
  ('single', 'Easy'),
  ('activities', 'Hard'),
  ('club', 'Easy'),
  ('example', 'Medium'),
  ('girls', 'Easy'),
  ('additional', 'Hard'),
  ('password', 'Medium'),
  ('latest', 'Easy'),
  ('something', 'Medium')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'spelling', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'spelling'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('road', 'Easy'),
  ('gift', 'Easy'),
  ('question', 'Medium'),
  ('changes', 'Medium'),
  ('night', 'Easy'),
  ('hard', 'Easy'),
  ('texas', 'Easy'),
  ('four', 'Easy'),
  ('poker', 'Easy'),
  ('status', 'Easy'),
  ('browse', 'Easy'),
  ('issue', 'Easy'),
  ('range', 'Easy'),
  ('building', 'Medium'),
  ('seller', 'Easy'),
  ('court', 'Easy'),
  ('february', 'Medium'),
  ('always', 'Easy'),
  ('result', 'Easy'),
  ('audio', 'Easy'),
  ('light', 'Easy'),
  ('write', 'Easy'),
  ('offer', 'Easy'),
  ('blue', 'Easy'),
  ('groups', 'Easy'),
  ('easy', 'Easy'),
  ('given', 'Easy'),
  ('files', 'Easy'),
  ('event', 'Easy'),
  ('release', 'Medium'),
  ('analysis', 'Medium'),
  ('request', 'Medium'),
  ('china', 'Easy'),
  ('making', 'Easy'),
  ('picture', 'Medium'),
  ('needs', 'Easy'),
  ('possible', 'Medium'),
  ('might', 'Easy'),
  ('professional', 'Hard'),
  ('month', 'Easy'),
  ('major', 'Easy'),
  ('star', 'Easy'),
  ('areas', 'Easy'),
  ('future', 'Easy'),
  ('space', 'Easy'),
  ('committee', 'Medium'),
  ('hand', 'Easy'),
  ('cards', 'Easy'),
  ('problems', 'Medium'),
  ('london', 'Easy'),
  ('washington', 'Hard'),
  ('meeting', 'Medium'),
  ('become', 'Easy'),
  ('interest', 'Medium'),
  ('child', 'Easy'),
  ('keep', 'Easy'),
  ('enter', 'Easy'),
  ('california', 'Hard'),
  ('share', 'Easy'),
  ('similar', 'Medium'),
  ('garden', 'Easy'),
  ('schools', 'Medium'),
  ('million', 'Medium'),
  ('added', 'Easy'),
  ('reference', 'Medium'),
  ('companies', 'Medium'),
  ('listed', 'Easy'),
  ('baby', 'Easy'),
  ('learning', 'Medium'),
  ('energy', 'Easy'),
  ('delivery', 'Medium'),
  ('popular', 'Medium'),
  ('term', 'Easy'),
  ('film', 'Easy'),
  ('stories', 'Medium'),
  ('computers', 'Medium'),
  ('journal', 'Medium'),
  ('reports', 'Medium'),
  ('welcome', 'Medium'),
  ('central', 'Medium'),
  ('images', 'Easy'),
  ('president', 'Medium'),
  ('notice', 'Easy'),
  ('original', 'Medium'),
  ('head', 'Easy'),
  ('radio', 'Easy'),
  ('until', 'Easy'),
  ('cell', 'Easy'),
  ('colour', 'Easy'),
  ('self', 'Easy'),
  ('council', 'Medium'),
  ('away', 'Easy'),
  ('includes', 'Medium'),
  ('track', 'Easy'),
  ('australia', 'Medium'),
  ('discussion', 'Hard'),
  ('archive', 'Medium'),
  ('once', 'Easy'),
  ('others', 'Easy'),
  ('entertainment', 'Hard')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'spelling', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'spelling'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('agreement', 'Medium'),
  ('format', 'Easy'),
  ('least', 'Easy'),
  ('society', 'Medium'),
  ('months', 'Easy'),
  ('safety', 'Easy'),
  ('friends', 'Medium'),
  ('sure', 'Easy'),
  ('trade', 'Easy'),
  ('edition', 'Medium'),
  ('cars', 'Easy'),
  ('messages', 'Medium'),
  ('marketing', 'Medium'),
  ('tell', 'Easy'),
  ('further', 'Medium'),
  ('updated', 'Medium'),
  ('association', 'Hard'),
  ('able', 'Easy'),
  ('having', 'Easy'),
  ('provides', 'Medium'),
  ('david', 'Easy'),
  ('already', 'Medium'),
  ('green', 'Easy'),
  ('studies', 'Medium'),
  ('close', 'Easy'),
  ('common', 'Easy'),
  ('drive', 'Easy'),
  ('specific', 'Medium'),
  ('several', 'Medium'),
  ('gold', 'Easy'),
  ('living', 'Easy'),
  ('collection', 'Hard'),
  ('called', 'Easy'),
  ('short', 'Easy'),
  ('arts', 'Easy'),
  ('display', 'Medium'),
  ('limited', 'Medium'),
  ('powered', 'Medium'),
  ('solutions', 'Medium'),
  ('means', 'Easy'),
  ('director', 'Medium'),
  ('daily', 'Easy'),
  ('beach', 'Easy'),
  ('past', 'Easy'),
  ('natural', 'Medium'),
  ('whether', 'Medium'),
  ('electronics', 'Hard'),
  ('five', 'Easy'),
  ('upon', 'Easy'),
  ('period', 'Easy'),
  ('planning', 'Medium'),
  ('database', 'Medium'),
  ('says', 'Easy'),
  ('official', 'Medium'),
  ('weather', 'Medium'),
  ('land', 'Easy'),
  ('average', 'Medium'),
  ('done', 'Easy'),
  ('technical', 'Medium'),
  ('window', 'Easy'),
  ('region', 'Easy'),
  ('island', 'Easy'),
  ('record', 'Easy'),
  ('direct', 'Easy'),
  ('conference', 'Hard'),
  ('environment', 'Hard'),
  ('records', 'Medium'),
  ('district', 'Medium'),
  ('calendar', 'Medium'),
  ('costs', 'Easy'),
  ('style', 'Easy'),
  ('front', 'Easy'),
  ('statement', 'Medium'),
  ('update', 'Easy'),
  ('parts', 'Easy'),
  ('ever', 'Easy'),
  ('early', 'Easy'),
  ('miles', 'Easy'),
  ('sound', 'Easy'),
  ('resource', 'Medium'),
  ('present', 'Medium'),
  ('applications', 'Hard'),
  ('either', 'Easy'),
  ('document', 'Medium'),
  ('word', 'Easy'),
  ('works', 'Easy'),
  ('material', 'Medium'),
  ('bill', 'Easy'),
  ('written', 'Medium'),
  ('talk', 'Easy'),
  ('federal', 'Medium'),
  ('rules', 'Easy'),
  ('final', 'Easy'),
  ('tickets', 'Medium'),
  ('thing', 'Easy'),
  ('requirements', 'Hard'),
  ('cheap', 'Easy'),
  ('kids', 'Easy'),
  ('finance', 'Medium'),
  ('true', 'Easy')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'spelling', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'spelling'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('minutes', 'Medium'),
  ('else', 'Easy'),
  ('mark', 'Easy'),
  ('third', 'Easy'),
  ('rock', 'Easy'),
  ('gifts', 'Easy'),
  ('europe', 'Easy'),
  ('reading', 'Medium'),
  ('topics', 'Easy'),
  ('individual', 'Hard'),
  ('tips', 'Easy'),
  ('plus', 'Easy'),
  ('auto', 'Easy'),
  ('cover', 'Easy'),
  ('usually', 'Medium'),
  ('edit', 'Easy'),
  ('together', 'Medium'),
  ('videos', 'Easy'),
  ('percent', 'Medium'),
  ('fast', 'Easy'),
  ('function', 'Medium'),
  ('fact', 'Easy'),
  ('unit', 'Easy'),
  ('getting', 'Medium'),
  ('global', 'Easy'),
  ('tech', 'Easy'),
  ('meet', 'Easy'),
  ('economic', 'Medium'),
  ('player', 'Easy'),
  ('projects', 'Medium'),
  ('lyrics', 'Easy'),
  ('often', 'Easy'),
  ('submit', 'Easy'),
  ('amount', 'Easy'),
  ('watch', 'Easy'),
  ('included', 'Medium'),
  ('feel', 'Easy'),
  ('though', 'Easy'),
  ('bank', 'Easy'),
  ('risk', 'Easy'),
  ('thanks', 'Easy'),
  ('everything', 'Hard'),
  ('deals', 'Easy'),
  ('various', 'Medium'),
  ('words', 'Easy'),
  ('production', 'Hard'),
  ('commercial', 'Hard'),
  ('james', 'Easy'),
  ('weight', 'Easy'),
  ('town', 'Easy'),
  ('heart', 'Easy'),
  ('received', 'Medium'),
  ('choose', 'Easy'),
  ('treatment', 'Medium'),
  ('archives', 'Medium'),
  ('points', 'Easy'),
  ('knowledge', 'Medium'),
  ('magazine', 'Medium'),
  ('error', 'Easy'),
  ('camera', 'Easy'),
  ('girl', 'Easy'),
  ('currently', 'Medium'),
  ('construction', 'Hard'),
  ('toys', 'Easy'),
  ('registered', 'Hard'),
  ('clear', 'Easy'),
  ('golf', 'Easy'),
  ('receive', 'Medium'),
  ('methods', 'Medium'),
  ('chapter', 'Medium'),
  ('makes', 'Easy'),
  ('protection', 'Hard'),
  ('policies', 'Medium'),
  ('wide', 'Easy'),
  ('beauty', 'Easy'),
  ('manager', 'Medium'),
  ('position', 'Medium'),
  ('taken', 'Easy'),
  ('sort', 'Easy'),
  ('models', 'Easy'),
  ('michael', 'Medium'),
  ('known', 'Easy'),
  ('half', 'Easy'),
  ('cases', 'Easy'),
  ('step', 'Easy'),
  ('engineering', 'Hard'),
  ('florida', 'Medium'),
  ('simple', 'Easy'),
  ('quick', 'Easy'),
  ('none', 'Easy'),
  ('wireless', 'Medium'),
  ('licence', 'Medium'),
  ('paul', 'Easy'),
  ('friday', 'Easy'),
  ('lake', 'Easy'),
  ('whole', 'Easy'),
  ('annual', 'Easy'),
  ('published', 'Medium'),
  ('later', 'Easy'),
  ('basic', 'Easy')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'spelling', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'spelling'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('shows', 'Easy'),
  ('corporate', 'Medium'),
  ('method', 'Easy'),
  ('purchase', 'Medium'),
  ('customers', 'Medium'),
  ('active', 'Easy'),
  ('response', 'Medium'),
  ('practice', 'Medium'),
  ('hardware', 'Medium'),
  ('figure', 'Easy'),
  ('materials', 'Medium'),
  ('fire', 'Easy'),
  ('holiday', 'Medium'),
  ('chat', 'Easy'),
  ('enough', 'Easy'),
  ('designed', 'Medium'),
  ('along', 'Easy'),
  ('among', 'Easy'),
  ('writing', 'Medium'),
  ('speed', 'Easy'),
  ('countries', 'Medium'),
  ('loss', 'Easy'),
  ('face', 'Easy'),
  ('brand', 'Easy'),
  ('discount', 'Medium'),
  ('higher', 'Easy'),
  ('effects', 'Medium'),
  ('created', 'Medium'),
  ('remember', 'Medium'),
  ('standards', 'Medium'),
  ('yellow', 'Easy'),
  ('political', 'Medium'),
  ('increase', 'Medium'),
  ('kingdom', 'Medium'),
  ('base', 'Easy'),
  ('near', 'Easy'),
  ('environmental', 'Hard'),
  ('thought', 'Medium'),
  ('stuff', 'Easy'),
  ('storage', 'Medium'),
  ('doing', 'Easy'),
  ('shoes', 'Easy'),
  ('entry', 'Easy'),
  ('stay', 'Easy'),
  ('nature', 'Easy'),
  ('orders', 'Easy'),
  ('availability', 'Hard'),
  ('africa', 'Easy'),
  ('summary', 'Medium'),
  ('turn', 'Easy'),
  ('mean', 'Easy'),
  ('growth', 'Easy'),
  ('notes', 'Easy'),
  ('agency', 'Easy'),
  ('king', 'Easy'),
  ('monday', 'Easy'),
  ('european', 'Medium'),
  ('activity', 'Medium'),
  ('copy', 'Easy'),
  ('although', 'Medium'),
  ('pics', 'Easy'),
  ('western', 'Medium'),
  ('income', 'Easy'),
  ('force', 'Easy'),
  ('cash', 'Easy'),
  ('employment', 'Hard'),
  ('overall', 'Medium'),
  ('river', 'Easy'),
  ('commission', 'Hard'),
  ('package', 'Medium'),
  ('contents', 'Medium'),
  ('seen', 'Easy'),
  ('players', 'Medium'),
  ('engine', 'Easy'),
  ('port', 'Easy'),
  ('album', 'Easy'),
  ('regional', 'Medium'),
  ('stop', 'Easy'),
  ('supplies', 'Medium'),
  ('started', 'Medium'),
  ('administration', 'Hard'),
  ('institute', 'Medium'),
  ('views', 'Easy'),
  ('plans', 'Easy'),
  ('double', 'Easy'),
  ('build', 'Easy'),
  ('screen', 'Easy'),
  ('exchange', 'Medium'),
  ('types', 'Easy'),
  ('soon', 'Easy'),
  ('sponsored', 'Medium'),
  ('lines', 'Easy'),
  ('electronic', 'Hard'),
  ('continue', 'Medium'),
  ('across', 'Easy'),
  ('benefits', 'Medium'),
  ('needed', 'Easy'),
  ('season', 'Easy'),
  ('apply', 'Easy'),
  ('someone', 'Medium')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'spelling', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'spelling'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('held', 'Easy'),
  ('anything', 'Medium'),
  ('printer', 'Medium'),
  ('condition', 'Medium'),
  ('effective', 'Medium'),
  ('believe', 'Medium'),
  ('organization', 'Hard'),
  ('effect', 'Easy'),
  ('asked', 'Easy'),
  ('mind', 'Easy'),
  ('sunday', 'Easy'),
  ('selection', 'Medium'),
  ('lost', 'Easy'),
  ('tour', 'Easy'),
  ('menu', 'Easy'),
  ('volume', 'Easy'),
  ('cross', 'Easy'),
  ('anyone', 'Easy'),
  ('hope', 'Easy'),
  ('silver', 'Easy'),
  ('corporation', 'Hard'),
  ('wish', 'Easy'),
  ('inside', 'Easy'),
  ('solution', 'Medium'),
  ('mature', 'Easy'),
  ('role', 'Easy'),
  ('rather', 'Easy'),
  ('weeks', 'Easy'),
  ('addition', 'Medium'),
  ('came', 'Easy'),
  ('supply', 'Easy'),
  ('nothing', 'Medium'),
  ('certain', 'Medium'),
  ('executive', 'Medium'),
  ('running', 'Medium'),
  ('lower', 'Easy'),
  ('necessary', 'Medium'),
  ('union', 'Easy'),
  ('jewellery', 'Medium'),
  ('according', 'Medium'),
  ('clothing', 'Medium'),
  ('particular', 'Hard'),
  ('fine', 'Easy'),
  ('names', 'Easy'),
  ('robert', 'Easy'),
  ('hour', 'Easy'),
  ('skills', 'Easy'),
  ('bush', 'Easy'),
  ('islands', 'Medium'),
  ('advice', 'Easy'),
  ('career', 'Easy'),
  ('military', 'Medium'),
  ('rental', 'Easy'),
  ('decision', 'Medium'),
  ('leave', 'Easy'),
  ('british', 'Medium'),
  ('huge', 'Easy'),
  ('woman', 'Easy'),
  ('facilities', 'Hard'),
  ('kind', 'Easy'),
  ('sellers', 'Medium'),
  ('middle', 'Easy'),
  ('move', 'Easy'),
  ('cable', 'Easy'),
  ('opportunities', 'Hard'),
  ('taking', 'Easy'),
  ('values', 'Easy'),
  ('division', 'Medium'),
  ('coming', 'Easy'),
  ('tuesday', 'Medium'),
  ('object', 'Easy'),
  ('appropriate', 'Hard'),
  ('machine', 'Medium'),
  ('logo', 'Easy'),
  ('length', 'Easy'),
  ('actually', 'Medium'),
  ('nice', 'Easy'),
  ('score', 'Easy'),
  ('statistics', 'Hard'),
  ('client', 'Easy'),
  ('returns', 'Medium'),
  ('capital', 'Medium'),
  ('follow', 'Easy'),
  ('sample', 'Easy'),
  ('investment', 'Hard'),
  ('sent', 'Easy'),
  ('shown', 'Easy'),
  ('saturday', 'Medium'),
  ('christmas', 'Medium'),
  ('culture', 'Medium'),
  ('band', 'Easy'),
  ('flash', 'Easy'),
  ('lead', 'Easy'),
  ('george', 'Easy'),
  ('choice', 'Easy'),
  ('went', 'Easy'),
  ('starting', 'Medium'),
  ('registration', 'Hard'),
  ('thursday', 'Medium'),
  ('courses', 'Medium')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'spelling', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'spelling'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('consumer', 'Medium'),
  ('airport', 'Medium'),
  ('foreign', 'Medium'),
  ('artist', 'Easy'),
  ('outside', 'Medium'),
  ('furniture', 'Medium'),
  ('levels', 'Easy'),
  ('channel', 'Medium'),
  ('letter', 'Easy'),
  ('mode', 'Easy'),
  ('phones', 'Easy'),
  ('ideas', 'Easy'),
  ('wednesday', 'Medium'),
  ('structure', 'Medium'),
  ('fund', 'Easy'),
  ('summer', 'Easy'),
  ('allow', 'Easy'),
  ('degree', 'Easy'),
  ('contract', 'Medium'),
  ('button', 'Easy'),
  ('releases', 'Medium'),
  ('homes', 'Easy'),
  ('super', 'Easy'),
  ('male', 'Easy'),
  ('matter', 'Easy'),
  ('custom', 'Easy'),
  ('virginia', 'Medium'),
  ('almost', 'Easy'),
  ('took', 'Easy'),
  ('located', 'Medium'),
  ('multiple', 'Medium'),
  ('asian', 'Easy'),
  ('distribution', 'Hard'),
  ('editor', 'Easy'),
  ('industrial', 'Hard'),
  ('cause', 'Easy'),
  ('potential', 'Medium'),
  ('song', 'Easy'),
  ('focus', 'Easy'),
  ('late', 'Easy'),
  ('fall', 'Easy'),
  ('featured', 'Medium'),
  ('idea', 'Easy'),
  ('rooms', 'Easy'),
  ('female', 'Easy'),
  ('responsible', 'Hard'),
  ('communications', 'Hard'),
  ('associated', 'Hard'),
  ('thomas', 'Easy'),
  ('primary', 'Medium'),
  ('numbers', 'Medium'),
  ('reason', 'Easy'),
  ('tool', 'Easy'),
  ('browser', 'Medium'),
  ('spring', 'Easy'),
  ('foundation', 'Hard'),
  ('answer', 'Easy'),
  ('voice', 'Easy'),
  ('friendly', 'Medium'),
  ('schedule', 'Medium'),
  ('documents', 'Medium'),
  ('communication', 'Hard'),
  ('purpose', 'Medium'),
  ('feature', 'Medium'),
  ('comes', 'Easy'),
  ('police', 'Easy'),
  ('everyone', 'Medium'),
  ('independent', 'Hard'),
  ('approach', 'Medium'),
  ('cameras', 'Medium'),
  ('brown', 'Easy'),
  ('physical', 'Medium'),
  ('operating', 'Medium'),
  ('hill', 'Easy'),
  ('maps', 'Easy'),
  ('medicine', 'Medium'),
  ('deal', 'Easy'),
  ('hold', 'Easy'),
  ('ratings', 'Medium'),
  ('chicago', 'Medium'),
  ('forms', 'Easy'),
  ('glass', 'Easy'),
  ('happy', 'Easy'),
  ('smith', 'Easy'),
  ('wanted', 'Easy'),
  ('developed', 'Medium'),
  ('thank', 'Easy'),
  ('safe', 'Easy'),
  ('unique', 'Easy'),
  ('survey', 'Easy'),
  ('prior', 'Easy'),
  ('telephone', 'Medium'),
  ('sport', 'Easy'),
  ('ready', 'Easy'),
  ('feed', 'Easy'),
  ('animal', 'Easy'),
  ('sources', 'Medium'),
  ('population', 'Hard'),
  ('regular', 'Medium'),
  ('secure', 'Easy')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'spelling', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'spelling'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('navigation', 'Hard'),
  ('operations', 'Hard'),
  ('therefore', 'Medium'),
  ('simply', 'Easy'),
  ('evidence', 'Medium'),
  ('station', 'Medium'),
  ('round', 'Easy'),
  ('favourite', 'Medium'),
  ('understand', 'Hard'),
  ('option', 'Easy'),
  ('master', 'Easy'),
  ('valley', 'Easy'),
  ('recently', 'Medium'),
  ('probably', 'Medium'),
  ('rentals', 'Medium'),
  ('built', 'Easy'),
  ('publications', 'Hard'),
  ('blood', 'Easy'),
  ('worldwide', 'Medium'),
  ('improve', 'Medium'),
  ('connection', 'Hard'),
  ('publisher', 'Medium'),
  ('hall', 'Easy'),
  ('larger', 'Easy'),
  ('anti', 'Easy'),
  ('networks', 'Medium'),
  ('earth', 'Easy'),
  ('parents', 'Medium'),
  ('impact', 'Easy'),
  ('transfer', 'Medium'),
  ('introduction', 'Hard'),
  ('kitchen', 'Medium'),
  ('strong', 'Easy'),
  ('carolina', 'Medium'),
  ('wedding', 'Medium'),
  ('properties', 'Hard'),
  ('hospital', 'Medium'),
  ('ground', 'Easy'),
  ('overview', 'Medium'),
  ('ship', 'Easy'),
  ('accommodation', 'Hard'),
  ('owners', 'Easy'),
  ('excellent', 'Medium'),
  ('paid', 'Easy'),
  ('perfect', 'Medium'),
  ('hair', 'Easy'),
  ('opportunity', 'Hard'),
  ('classic', 'Medium'),
  ('basis', 'Easy'),
  ('command', 'Medium'),
  ('cities', 'Easy'),
  ('william', 'Medium'),
  ('express', 'Medium'),
  ('award', 'Easy'),
  ('distance', 'Medium'),
  ('tree', 'Easy'),
  ('peter', 'Easy'),
  ('assessment', 'Hard'),
  ('ensure', 'Easy'),
  ('thus', 'Easy'),
  ('wall', 'Easy'),
  ('involved', 'Medium'),
  ('extra', 'Easy'),
  ('especially', 'Hard'),
  ('interface', 'Medium'),
  ('partners', 'Medium'),
  ('budget', 'Easy'),
  ('rated', 'Easy'),
  ('guides', 'Easy'),
  ('success', 'Medium'),
  ('maximum', 'Medium'),
  ('operation', 'Medium'),
  ('existing', 'Medium'),
  ('quite', 'Easy'),
  ('selected', 'Medium'),
  ('patients', 'Medium'),
  ('restaurants', 'Hard'),
  ('beautiful', 'Medium'),
  ('warning', 'Medium'),
  ('wine', 'Easy'),
  ('locations', 'Medium'),
  ('horse', 'Easy'),
  ('vote', 'Easy'),
  ('forward', 'Medium'),
  ('flowers', 'Medium'),
  ('stars', 'Easy'),
  ('significant', 'Hard'),
  ('lists', 'Easy'),
  ('technologies', 'Hard'),
  ('owner', 'Easy'),
  ('retail', 'Easy'),
  ('animals', 'Medium'),
  ('useful', 'Easy'),
  ('directly', 'Medium'),
  ('manufacturer', 'Hard'),
  ('ways', 'Easy'),
  ('providing', 'Medium'),
  ('rule', 'Easy'),
  ('housing', 'Medium'),
  ('takes', 'Easy')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'spelling', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'spelling'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('bring', 'Easy'),
  ('catalog', 'Medium'),
  ('searches', 'Medium'),
  ('trying', 'Easy'),
  ('mother', 'Easy'),
  ('authority', 'Medium'),
  ('considered', 'Hard'),
  ('told', 'Easy'),
  ('traffic', 'Medium'),
  ('programme', 'Medium'),
  ('joined', 'Easy'),
  ('input', 'Easy'),
  ('strategy', 'Medium'),
  ('feet', 'Easy'),
  ('agent', 'Easy'),
  ('valid', 'Easy'),
  ('modern', 'Easy'),
  ('senior', 'Easy'),
  ('teaching', 'Medium'),
  ('door', 'Easy'),
  ('grand', 'Easy'),
  ('testing', 'Medium'),
  ('trial', 'Easy'),
  ('charge', 'Easy'),
  ('units', 'Easy'),
  ('instead', 'Medium'),
  ('cool', 'Easy'),
  ('normal', 'Easy'),
  ('wrote', 'Easy'),
  ('enterprise', 'Hard'),
  ('ships', 'Easy'),
  ('entire', 'Easy'),
  ('educational', 'Hard'),
  ('leading', 'Medium'),
  ('metal', 'Easy'),
  ('positive', 'Medium'),
  ('fitness', 'Medium'),
  ('opinion', 'Medium'),
  ('asia', 'Easy'),
  ('football', 'Medium'),
  ('abstract', 'Medium'),
  ('uses', 'Easy'),
  ('output', 'Easy'),
  ('funds', 'Easy'),
  ('greater', 'Medium'),
  ('likely', 'Easy'),
  ('develop', 'Medium'),
  ('employees', 'Medium'),
  ('artists', 'Medium'),
  ('alternative', 'Hard'),
  ('processing', 'Hard'),
  ('responsibility', 'Hard'),
  ('resolution', 'Hard'),
  ('guest', 'Easy'),
  ('seems', 'Easy'),
  ('publication', 'Hard'),
  ('pass', 'Easy'),
  ('relations', 'Medium'),
  ('trust', 'Easy'),
  ('contains', 'Medium'),
  ('session', 'Medium'),
  ('multi', 'Easy'),
  ('photography', 'Hard'),
  ('republic', 'Medium'),
  ('fees', 'Easy'),
  ('components', 'Hard'),
  ('vacation', 'Medium'),
  ('century', 'Medium'),
  ('academic', 'Medium'),
  ('assistance', 'Hard'),
  ('completed', 'Medium'),
  ('skin', 'Easy'),
  ('graphics', 'Medium'),
  ('indian', 'Easy'),
  ('prev', 'Easy'),
  ('mary', 'Easy'),
  ('expected', 'Medium'),
  ('ring', 'Easy'),
  ('grade', 'Easy'),
  ('mountain', 'Medium'),
  ('organizations', 'Hard'),
  ('filter', 'Easy'),
  ('mailing', 'Medium'),
  ('vehicle', 'Medium'),
  ('longer', 'Easy'),
  ('consider', 'Medium'),
  ('northern', 'Medium'),
  ('behind', 'Easy'),
  ('panel', 'Easy'),
  ('floor', 'Easy'),
  ('buying', 'Easy'),
  ('match', 'Easy'),
  ('proposed', 'Medium'),
  ('default', 'Medium'),
  ('require', 'Medium'),
  ('boys', 'Easy'),
  ('outdoor', 'Medium'),
  ('deep', 'Easy'),
  ('morning', 'Medium'),
  ('otherwise', 'Medium')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'spelling', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'spelling'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('allows', 'Easy'),
  ('rest', 'Easy'),
  ('protein', 'Medium'),
  ('plant', 'Easy'),
  ('reported', 'Medium'),
  ('transportation', 'Hard'),
  ('pool', 'Easy'),
  ('mini', 'Easy'),
  ('politics', 'Medium'),
  ('partner', 'Medium'),
  ('disclaimer', 'Hard'),
  ('authors', 'Medium'),
  ('boards', 'Easy'),
  ('faculty', 'Medium'),
  ('parties', 'Medium'),
  ('fish', 'Easy'),
  ('membership', 'Hard'),
  ('mission', 'Medium'),
  ('string', 'Easy'),
  ('sense', 'Easy'),
  ('modified', 'Medium'),
  ('pack', 'Easy'),
  ('released', 'Medium'),
  ('stage', 'Easy'),
  ('internal', 'Medium'),
  ('goods', 'Easy'),
  ('recommended', 'Hard'),
  ('born', 'Easy'),
  ('unless', 'Easy'),
  ('richard', 'Medium'),
  ('detailed', 'Medium'),
  ('race', 'Easy'),
  ('approved', 'Medium'),
  ('background', 'Hard'),
  ('target', 'Easy'),
  ('except', 'Easy'),
  ('character', 'Medium'),
  ('maintenance', 'Hard'),
  ('ability', 'Medium'),
  ('maybe', 'Easy'),
  ('functions', 'Medium'),
  ('moving', 'Easy'),
  ('brands', 'Easy'),
  ('places', 'Easy'),
  ('pretty', 'Easy'),
  ('trademarks', 'Hard'),
  ('southern', 'Medium'),
  ('yourself', 'Medium'),
  ('winter', 'Easy'),
  ('battery', 'Medium'),
  ('youth', 'Easy'),
  ('pressure', 'Medium'),
  ('submitted', 'Medium'),
  ('boston', 'Easy'),
  ('debt', 'Easy'),
  ('keywords', 'Medium'),
  ('medium', 'Easy'),
  ('television', 'Hard'),
  ('interested', 'Hard'),
  ('core', 'Easy'),
  ('break', 'Easy'),
  ('purposes', 'Medium'),
  ('throughout', 'Hard'),
  ('sets', 'Easy'),
  ('dance', 'Easy'),
  ('wood', 'Easy'),
  ('itself', 'Easy'),
  ('defined', 'Medium'),
  ('papers', 'Easy'),
  ('playing', 'Medium'),
  ('awards', 'Easy'),
  ('studio', 'Easy'),
  ('reader', 'Easy'),
  ('virtual', 'Medium'),
  ('device', 'Easy'),
  ('established', 'Hard'),
  ('answers', 'Medium'),
  ('rent', 'Easy'),
  ('remote', 'Easy'),
  ('dark', 'Easy'),
  ('programming', 'Hard'),
  ('external', 'Medium'),
  ('apple', 'Easy'),
  ('regarding', 'Medium'),
  ('instructions', 'Hard'),
  ('offered', 'Medium'),
  ('theory', 'Easy'),
  ('enjoy', 'Easy'),
  ('remove', 'Easy'),
  ('surface', 'Medium'),
  ('minimum', 'Medium'),
  ('visual', 'Easy'),
  ('host', 'Easy'),
  ('variety', 'Medium'),
  ('teachers', 'Medium'),
  ('martin', 'Easy'),
  ('manual', 'Easy'),
  ('block', 'Easy'),
  ('subjects', 'Medium'),
  ('agents', 'Easy')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'spelling', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'spelling'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('home', 'Easy'),
  ('page', 'Easy'),
  ('time', 'Easy'),
  ('site', 'Easy'),
  ('news', 'Easy'),
  ('contact', 'Medium'),
  ('here', 'Easy'),
  ('help', 'Easy'),
  ('view', 'Easy'),
  ('price', 'Easy'),
  ('date', 'Easy'),
  ('back', 'Easy'),
  ('people', 'Medium'),
  ('list', 'Easy'),
  ('name', 'Easy'),
  ('state', 'Easy'),
  ('year', 'Easy'),
  ('health', 'Medium'),
  ('world', 'Easy'),
  ('work', 'Easy'),
  ('music', 'Easy'),
  ('make', 'Easy'),
  ('product', 'Medium'),
  ('post', 'Easy'),
  ('number', 'Medium'),
  ('message', 'Medium'),
  ('video', 'Easy'),
  ('public', 'Medium'),
  ('school', 'Medium'),
  ('review', 'Medium'),
  ('order', 'Easy'),
  ('book', 'Easy'),
  ('company', 'Medium'),
  ('group', 'Easy'),
  ('need', 'Easy'),
  ('research', 'Challenge'),
  ('january', 'Medium'),
  ('mail', 'Easy'),
  ('program', 'Medium'),
  ('life', 'Easy'),
  ('games', 'Easy'),
  ('part', 'Easy'),
  ('hotel', 'Easy'),
  ('item', 'Easy'),
  ('store', 'Easy'),
  ('travel', 'Medium'),
  ('report', 'Medium'),
  ('member', 'Medium'),
  ('line', 'Easy'),
  ('type', 'Easy'),
  ('office', 'Medium'),
  ('address', 'Medium'),
  ('states', 'Medium'),
  ('area', 'Easy'),
  ('want', 'Easy'),
  ('subject', 'Medium'),
  ('family', 'Medium'),
  ('show', 'Easy'),
  ('check', 'Easy'),
  ('prices', 'Medium'),
  ('index', 'Easy'),
  ('being', 'Easy'),
  ('women', 'Easy'),
  ('much', 'Easy'),
  ('sign', 'Easy'),
  ('file', 'Easy'),
  ('link', 'Easy'),
  ('today', 'Easy'),
  ('south', 'Easy'),
  ('case', 'Easy'),
  ('project', 'Medium'),
  ('pages', 'Easy'),
  ('version', 'Medium'),
  ('house', 'Easy'),
  ('photo', 'Easy'),
  ('game', 'Easy'),
  ('power', 'Easy'),
  ('care', 'Easy'),
  ('network', 'Medium'),
  ('computer', 'Challenge'),
  ('total', 'Easy'),
  ('place', 'Easy'),
  ('access', 'Medium'),
  ('north', 'Easy'),
  ('resources', 'Challenge'),
  ('control', 'Medium'),
  ('water', 'Easy'),
  ('history', 'Medium'),
  ('pictures', 'Challenge'),
  ('size', 'Easy'),
  ('guide', 'Easy'),
  ('shop', 'Easy'),
  ('directory', 'Challenge'),
  ('board', 'Easy'),
  ('change', 'Medium'),
  ('text', 'Easy'),
  ('rating', 'Medium'),
  ('rate', 'Easy'),
  ('children', 'Challenge'),
  ('return', 'Medium')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'password', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'password'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('account', 'Medium'),
  ('times', 'Easy'),
  ('sites', 'Easy'),
  ('profile', 'Medium'),
  ('form', 'Easy'),
  ('love', 'Easy'),
  ('call', 'Easy'),
  ('image', 'Easy'),
  ('title', 'Easy'),
  ('property', 'Challenge'),
  ('class', 'Easy'),
  ('money', 'Easy'),
  ('listing', 'Medium'),
  ('country', 'Medium'),
  ('visit', 'Easy'),
  ('customer', 'Challenge'),
  ('december', 'Challenge'),
  ('college', 'Medium'),
  ('value', 'Easy'),
  ('article', 'Medium'),
  ('card', 'Easy'),
  ('food', 'Easy'),
  ('source', 'Medium'),
  ('press', 'Easy'),
  ('sale', 'Easy'),
  ('print', 'Easy'),
  ('course', 'Medium'),
  ('process', 'Medium'),
  ('room', 'Easy'),
  ('stock', 'Easy'),
  ('training', 'Challenge'),
  ('credit', 'Medium'),
  ('point', 'Easy'),
  ('west', 'Easy'),
  ('sales', 'Easy'),
  ('look', 'Easy'),
  ('team', 'Easy'),
  ('thread', 'Medium'),
  ('week', 'Easy'),
  ('category', 'Challenge'),
  ('note', 'Easy'),
  ('table', 'Easy'),
  ('register', 'Challenge'),
  ('june', 'Easy'),
  ('october', 'Medium'),
  ('november', 'Challenge'),
  ('market', 'Medium'),
  ('library', 'Medium'),
  ('start', 'Easy'),
  ('series', 'Medium'),
  ('model', 'Easy'),
  ('features', 'Challenge'),
  ('industry', 'Challenge'),
  ('plan', 'Easy'),
  ('human', 'Easy'),
  ('second', 'Medium'),
  ('cost', 'Easy'),
  ('march', 'Easy'),
  ('september', 'Challenge'),
  ('july', 'Easy'),
  ('test', 'Easy'),
  ('friend', 'Medium'),
  ('study', 'Easy'),
  ('cart', 'Easy'),
  ('staff', 'Easy'),
  ('articles', 'Challenge'),
  ('feedback', 'Challenge'),
  ('play', 'Easy'),
  ('issues', 'Medium'),
  ('april', 'Easy'),
  ('street', 'Medium'),
  ('topic', 'Easy'),
  ('standard', 'Challenge'),
  ('person', 'Medium'),
  ('party', 'Easy'),
  ('student', 'Medium'),
  ('park', 'Easy'),
  ('stores', 'Medium'),
  ('side', 'Easy'),
  ('problem', 'Medium'),
  ('memory', 'Medium'),
  ('august', 'Medium'),
  ('language', 'Challenge'),
  ('story', 'Easy'),
  ('rates', 'Easy'),
  ('body', 'Easy'),
  ('field', 'Easy'),
  ('east', 'Easy'),
  ('paper', 'Easy'),
  ('club', 'Easy'),
  ('example', 'Medium'),
  ('password', 'Challenge'),
  ('road', 'Easy'),
  ('changes', 'Medium'),
  ('night', 'Easy'),
  ('status', 'Medium'),
  ('issue', 'Easy'),
  ('range', 'Easy'),
  ('building', 'Challenge'),
  ('court', 'Easy')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'password', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'password'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('february', 'Challenge'),
  ('result', 'Medium'),
  ('light', 'Easy'),
  ('offer', 'Easy'),
  ('files', 'Easy'),
  ('event', 'Easy'),
  ('release', 'Medium'),
  ('analysis', 'Challenge'),
  ('request', 'Medium'),
  ('picture', 'Medium'),
  ('month', 'Easy'),
  ('major', 'Easy'),
  ('star', 'Easy'),
  ('future', 'Medium'),
  ('space', 'Easy'),
  ('committee', 'Challenge'),
  ('hand', 'Easy'),
  ('meeting', 'Medium'),
  ('interest', 'Challenge'),
  ('child', 'Easy'),
  ('share', 'Easy'),
  ('garden', 'Medium'),
  ('million', 'Medium'),
  ('baby', 'Easy'),
  ('learning', 'Challenge'),
  ('energy', 'Medium'),
  ('delivery', 'Challenge'),
  ('term', 'Easy'),
  ('film', 'Easy'),
  ('journal', 'Medium'),
  ('images', 'Medium'),
  ('president', 'Challenge'),
  ('notice', 'Medium'),
  ('head', 'Easy'),
  ('radio', 'Easy'),
  ('cell', 'Easy'),
  ('self', 'Easy'),
  ('track', 'Easy'),
  ('discussion', 'Challenge'),
  ('others', 'Medium'),
  ('format', 'Medium'),
  ('society', 'Medium'),
  ('safety', 'Medium'),
  ('trade', 'Easy'),
  ('messages', 'Challenge'),
  ('drive', 'Easy'),
  ('gold', 'Easy'),
  ('display', 'Medium'),
  ('means', 'Easy'),
  ('beach', 'Easy'),
  ('period', 'Medium'),
  ('official', 'Challenge'),
  ('weather', 'Medium'),
  ('land', 'Easy'),
  ('average', 'Medium'),
  ('window', 'Medium'),
  ('region', 'Medium'),
  ('island', 'Medium'),
  ('record', 'Medium'),
  ('district', 'Challenge'),
  ('calendar', 'Challenge'),
  ('front', 'Easy'),
  ('update', 'Medium'),
  ('miles', 'Easy'),
  ('sound', 'Easy'),
  ('resource', 'Challenge'),
  ('present', 'Medium'),
  ('word', 'Easy'),
  ('material', 'Challenge'),
  ('bill', 'Easy'),
  ('talk', 'Easy'),
  ('rules', 'Easy'),
  ('thing', 'Easy'),
  ('minutes', 'Medium'),
  ('mark', 'Easy'),
  ('rock', 'Easy'),
  ('reading', 'Medium'),
  ('auto', 'Easy'),
  ('cover', 'Easy'),
  ('percent', 'Medium'),
  ('fact', 'Easy'),
  ('unit', 'Easy'),
  ('meet', 'Easy'),
  ('amount', 'Medium'),
  ('watch', 'Easy'),
  ('bank', 'Easy'),
  ('thanks', 'Medium'),
  ('weight', 'Medium'),
  ('town', 'Easy'),
  ('heart', 'Easy'),
  ('knowledge', 'Challenge'),
  ('magazine', 'Challenge'),
  ('error', 'Easy'),
  ('camera', 'Medium'),
  ('girl', 'Easy'),
  ('chapter', 'Medium'),
  ('makes', 'Easy'),
  ('manager', 'Medium'),
  ('sort', 'Easy'),
  ('half', 'Easy')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'password', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'password'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('cases', 'Easy'),
  ('step', 'Easy'),
  ('friday', 'Medium'),
  ('lake', 'Easy'),
  ('method', 'Medium'),
  ('purchase', 'Challenge'),
  ('response', 'Challenge'),
  ('practice', 'Challenge'),
  ('hardware', 'Challenge'),
  ('figure', 'Medium'),
  ('fire', 'Easy'),
  ('writing', 'Medium'),
  ('speed', 'Easy'),
  ('loss', 'Easy'),
  ('face', 'Easy'),
  ('discount', 'Challenge'),
  ('increase', 'Challenge'),
  ('base', 'Easy'),
  ('thought', 'Medium'),
  ('stuff', 'Easy'),
  ('storage', 'Medium'),
  ('shoes', 'Easy'),
  ('entry', 'Easy'),
  ('nature', 'Medium'),
  ('summary', 'Medium'),
  ('turn', 'Easy'),
  ('growth', 'Medium'),
  ('notes', 'Easy'),
  ('monday', 'Medium'),
  ('copy', 'Easy'),
  ('income', 'Medium'),
  ('force', 'Easy'),
  ('cash', 'Easy'),
  ('river', 'Easy'),
  ('commission', 'Challenge'),
  ('package', 'Medium'),
  ('engine', 'Medium'),
  ('port', 'Easy'),
  ('stop', 'Easy'),
  ('screen', 'Medium'),
  ('exchange', 'Challenge'),
  ('types', 'Easy'),
  ('lines', 'Easy'),
  ('season', 'Medium'),
  ('effect', 'Medium'),
  ('mind', 'Easy'),
  ('sunday', 'Medium'),
  ('tour', 'Easy'),
  ('menu', 'Easy'),
  ('volume', 'Medium'),
  ('cross', 'Easy'),
  ('hope', 'Easy'),
  ('silver', 'Medium'),
  ('wish', 'Easy'),
  ('supply', 'Medium'),
  ('nothing', 'Medium'),
  ('executive', 'Challenge'),
  ('union', 'Easy'),
  ('clothing', 'Challenge'),
  ('names', 'Easy'),
  ('hour', 'Easy'),
  ('bush', 'Easy'),
  ('career', 'Medium'),
  ('military', 'Challenge'),
  ('decision', 'Challenge'),
  ('leave', 'Easy'),
  ('woman', 'Easy'),
  ('move', 'Easy'),
  ('cable', 'Easy'),
  ('values', 'Medium'),
  ('division', 'Challenge'),
  ('tuesday', 'Medium'),
  ('object', 'Medium'),
  ('machine', 'Medium'),
  ('length', 'Medium'),
  ('score', 'Easy'),
  ('capital', 'Medium'),
  ('sample', 'Medium'),
  ('saturday', 'Challenge'),
  ('band', 'Easy'),
  ('flash', 'Easy'),
  ('lead', 'Easy'),
  ('choice', 'Medium'),
  ('thursday', 'Challenge'),
  ('courses', 'Medium'),
  ('airport', 'Medium'),
  ('levels', 'Medium'),
  ('channel', 'Medium'),
  ('letter', 'Medium'),
  ('mode', 'Easy'),
  ('structure', 'Challenge'),
  ('fund', 'Easy'),
  ('summer', 'Medium'),
  ('degree', 'Medium'),
  ('contract', 'Challenge'),
  ('button', 'Medium'),
  ('releases', 'Challenge'),
  ('homes', 'Easy'),
  ('male', 'Easy'),
  ('matter', 'Medium')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'password', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'password'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('custom', 'Medium'),
  ('editor', 'Medium'),
  ('cause', 'Easy'),
  ('song', 'Easy'),
  ('focus', 'Easy'),
  ('fall', 'Easy'),
  ('idea', 'Easy'),
  ('reason', 'Medium'),
  ('tool', 'Easy'),
  ('spring', 'Medium'),
  ('answer', 'Medium'),
  ('voice', 'Easy'),
  ('schedule', 'Challenge'),
  ('purpose', 'Medium'),
  ('feature', 'Medium'),
  ('police', 'Medium'),
  ('approach', 'Challenge'),
  ('hill', 'Easy'),
  ('medicine', 'Challenge'),
  ('deal', 'Easy'),
  ('hold', 'Easy'),
  ('glass', 'Easy'),
  ('survey', 'Medium'),
  ('telephone', 'Challenge'),
  ('sport', 'Easy'),
  ('feed', 'Easy'),
  ('animal', 'Medium'),
  ('sources', 'Medium'),
  ('round', 'Easy'),
  ('master', 'Medium'),
  ('valley', 'Medium'),
  ('blood', 'Easy'),
  ('hall', 'Easy'),
  ('earth', 'Easy'),
  ('impact', 'Medium'),
  ('transfer', 'Challenge'),
  ('wedding', 'Medium'),
  ('hospital', 'Challenge'),
  ('ground', 'Medium'),
  ('perfect', 'Medium'),
  ('hair', 'Easy'),
  ('basis', 'Easy'),
  ('command', 'Medium'),
  ('award', 'Easy'),
  ('tree', 'Easy'),
  ('wall', 'Easy'),
  ('interface', 'Challenge'),
  ('budget', 'Medium'),
  ('guides', 'Medium'),
  ('success', 'Medium'),
  ('maximum', 'Medium'),
  ('warning', 'Medium'),
  ('wine', 'Easy'),
  ('owner', 'Easy'),
  ('rule', 'Easy'),
  ('housing', 'Medium'),
  ('catalog', 'Medium'),
  ('mother', 'Medium'),
  ('traffic', 'Medium'),
  ('input', 'Easy'),
  ('feet', 'Easy'),
  ('agent', 'Easy'),
  ('teaching', 'Challenge'),
  ('door', 'Easy'),
  ('trial', 'Easy'),
  ('charge', 'Medium'),
  ('metal', 'Easy'),
  ('opinion', 'Medium'),
  ('uses', 'Easy'),
  ('output', 'Medium'),
  ('employees', 'Challenge'),
  ('guest', 'Easy'),
  ('pass', 'Easy'),
  ('trust', 'Easy'),
  ('session', 'Medium'),
  ('fees', 'Easy'),
  ('skin', 'Easy'),
  ('ring', 'Easy'),
  ('grade', 'Easy'),
  ('mountain', 'Challenge'),
  ('filter', 'Medium'),
  ('vehicle', 'Medium'),
  ('panel', 'Easy'),
  ('floor', 'Easy'),
  ('match', 'Easy'),
  ('default', 'Medium'),
  ('morning', 'Medium'),
  ('rest', 'Easy'),
  ('plant', 'Easy'),
  ('pool', 'Easy'),
  ('partner', 'Medium'),
  ('fish', 'Easy'),
  ('mission', 'Medium'),
  ('string', 'Medium'),
  ('sense', 'Easy'),
  ('pack', 'Easy'),
  ('stage', 'Easy'),
  ('goods', 'Easy'),
  ('race', 'Easy'),
  ('background', 'Challenge')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'password', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'password'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('target', 'Medium'),
  ('character', 'Challenge'),
  ('places', 'Medium'),
  ('winter', 'Medium'),
  ('battery', 'Medium'),
  ('pressure', 'Challenge'),
  ('debt', 'Easy'),
  ('medium', 'Medium'),
  ('television', 'Challenge'),
  ('core', 'Easy'),
  ('break', 'Easy'),
  ('purposes', 'Challenge'),
  ('wood', 'Easy'),
  ('reader', 'Medium'),
  ('device', 'Medium'),
  ('apple', 'Easy'),
  ('theory', 'Medium'),
  ('surface', 'Medium'),
  ('minimum', 'Medium'),
  ('variety', 'Medium'),
  ('manual', 'Medium'),
  ('block', 'Easy'),
  ('repair', 'Medium'),
  ('steel', 'Easy'),
  ('associates', 'Challenge'),
  ('updates', 'Medium'),
  ('sector', 'Medium'),
  ('father', 'Medium'),
  ('officer', 'Medium'),
  ('driver', 'Medium'),
  ('respect', 'Medium'),
  ('restaurant', 'Challenge'),
  ('trip', 'Easy'),
  ('worth', 'Easy'),
  ('procedures', 'Challenge'),
  ('eyes', 'Easy'),
  ('farm', 'Easy'),
  ('peace', 'Easy'),
  ('coast', 'Easy'),
  ('benefit', 'Medium'),
  ('progress', 'Challenge'),
  ('funding', 'Medium'),
  ('devices', 'Medium'),
  ('grant', 'Easy'),
  ('transport', 'Challenge'),
  ('zone', 'Easy'),
  ('references', 'Challenge'),
  ('jack', 'Easy'),
  ('flow', 'Easy'),
  ('setting', 'Medium'),
  ('scale', 'Easy'),
  ('stand', 'Easy'),
  ('economy', 'Medium'),
  ('frame', 'Easy'),
  ('secretary', 'Challenge'),
  ('path', 'Easy'),
  ('employee', 'Challenge'),
  ('chief', 'Easy'),
  ('bottom', 'Medium'),
  ('magazines', 'Challenge'),
  ('packages', 'Challenge'),
  ('detail', 'Medium'),
  ('switch', 'Medium'),
  ('titles', 'Medium'),
  ('guidelines', 'Challenge'),
  ('justice', 'Medium'),
  ('basket', 'Medium'),
  ('square', 'Medium'),
  ('skip', 'Easy'),
  ('army', 'Easy'),
  ('gear', 'Easy'),
  ('piece', 'Easy'),
  ('sheet', 'Easy'),
  ('jump', 'Easy'),
  ('module', 'Medium'),
  ('fashion', 'Medium'),
  ('monitor', 'Medium'),
  ('forest', 'Medium'),
  ('couple', 'Medium'),
  ('vision', 'Medium'),
  ('ball', 'Easy'),
  ('ending', 'Medium'),
  ('goal', 'Easy'),
  ('wind', 'Easy'),
  ('sciences', 'Challenge'),
  ('emergency', 'Challenge'),
  ('lives', 'Easy'),
  ('currency', 'Challenge'),
  ('leather', 'Medium'),
  ('patient', 'Medium'),
  ('stone', 'Easy'),
  ('satellite', 'Challenge'),
  ('village', 'Medium'),
  ('pain', 'Easy'),
  ('edge', 'Easy'),
  ('root', 'Easy'),
  ('pink', 'Easy'),
  ('shot', 'Easy'),
  ('initial', 'Medium'),
  ('label', 'Easy')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'password', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'password'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('waste', 'Easy'),
  ('minute', 'Medium'),
  ('dictionary', 'Challenge'),
  ('accounting', 'Challenge'),
  ('chair', 'Easy'),
  ('effort', 'Medium'),
  ('phase', 'Easy'),
  ('motor', 'Easy'),
  ('shirt', 'Easy'),
  ('foot', 'Easy'),
  ('mass', 'Easy'),
  ('crime', 'Easy'),
  ('count', 'Easy'),
  ('techniques', 'Challenge'),
  ('religion', 'Challenge'),
  ('claim', 'Easy'),
  ('permission', 'Challenge'),
  ('patch', 'Easy'),
  ('heat', 'Easy'),
  ('measures', 'Challenge'),
  ('miss', 'Easy'),
  ('chemical', 'Challenge'),
  ('task', 'Easy'),
  ('component', 'Challenge'),
  ('exercise', 'Challenge'),
  ('leader', 'Medium'),
  ('diamond', 'Medium'),
  ('keyword', 'Medium'),
  ('flight', 'Medium'),
  ('congress', 'Challenge'),
  ('fuel', 'Easy'),
  ('walk', 'Easy'),
  ('wait', 'Easy'),
  ('pocket', 'Medium'),
  ('rose', 'Easy'),
  ('freedom', 'Medium'),
  ('joint', 'Easy'),
  ('attorney', 'Challenge'),
  ('factor', 'Medium'),
  ('stream', 'Medium'),
  ('pick', 'Easy'),
  ('dates', 'Easy'),
  ('prime', 'Easy'),
  ('limit', 'Easy'),
  ('creek', 'Easy'),
  ('practices', 'Challenge'),
  ('platform', 'Challenge'),
  ('load', 'Easy'),
  ('labor', 'Easy'),
  ('defense', 'Medium'),
  ('machines', 'Challenge'),
  ('recovery', 'Challenge'),
  ('merchant', 'Challenge'),
  ('expert', 'Medium'),
  ('drop', 'Easy'),
  ('languages', 'Challenge'),
  ('orange', 'Medium'),
  ('vehicles', 'Challenge'),
  ('examples', 'Challenge'),
  ('saying', 'Medium'),
  ('challenge', 'Challenge'),
  ('touch', 'Easy'),
  ('branch', 'Medium'),
  ('charges', 'Medium'),
  ('mount', 'Easy'),
  ('ones', 'Easy'),
  ('corner', 'Medium'),
  ('rank', 'Easy'),
  ('birth', 'Easy'),
  ('quarter', 'Medium'),
  ('procedure', 'Challenge'),
  ('tables', 'Medium'),
  ('column', 'Medium'),
  ('chain', 'Easy'),
  ('reach', 'Easy'),
  ('comparison', 'Challenge'),
  ('inch', 'Easy'),
  ('attack', 'Medium'),
  ('damage', 'Medium'),
  ('reserve', 'Medium'),
  ('plastic', 'Medium'),
  ('produce', 'Medium'),
  ('snow', 'Easy'),
  ('truth', 'Easy'),
  ('counter', 'Medium'),
  ('failure', 'Medium'),
  ('dollar', 'Medium'),
  ('camp', 'Easy'),
  ('bridge', 'Medium'),
  ('approval', 'Challenge'),
  ('draft', 'Easy'),
  ('chart', 'Easy'),
  ('offering', 'Challenge'),
  ('profit', 'Medium'),
  ('assistant', 'Challenge'),
  ('wholesale', 'Challenge'),
  ('codes', 'Easy'),
  ('kinds', 'Easy'),
  ('extension', 'Challenge'),
  ('fort', 'Easy')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'password', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'password'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('forces', 'Medium'),
  ('brother', 'Medium'),
  ('pattern', 'Medium'),
  ('boat', 'Easy'),
  ('laser', 'Easy'),
  ('sponsor', 'Medium'),
  ('warranty', 'Challenge'),
  ('evening', 'Medium'),
  ('assembly', 'Challenge'),
  ('signal', 'Medium'),
  ('brain', 'Easy'),
  ('cast', 'Easy'),
  ('flower', 'Medium'),
  ('felt', 'Easy'),
  ('personnel', 'Challenge'),
  ('flag', 'Easy'),
  ('advantage', 'Challenge'),
  ('hello', 'Easy'),
  ('atom', 'Easy'),
  ('iron', 'Easy'),
  ('alert', 'Easy'),
  ('interview', 'Challenge'),
  ('disk', 'Easy'),
  ('handle', 'Medium'),
  ('desk', 'Easy'),
  ('vice', 'Easy'),
  ('associate', 'Challenge'),
  ('truck', 'Easy'),
  ('behaviour', 'Challenge'),
  ('measure', 'Medium'),
  ('duty', 'Easy'),
  ('bear', 'Easy'),
  ('laboratory', 'Challenge'),
  ('ocean', 'Easy'),
  ('lack', 'Easy'),
  ('depth', 'Easy'),
  ('train', 'Easy'),
  ('concept', 'Medium'),
  ('checkout', 'Challenge'),
  ('origin', 'Medium'),
  ('route', 'Easy'),
  ('blow', 'Easy'),
  ('battle', 'Medium'),
  ('clip', 'Easy'),
  ('speech', 'Medium'),
  ('wire', 'Easy'),
  ('principles', 'Challenge'),
  ('tape', 'Easy'),
  ('judge', 'Easy'),
  ('acid', 'Easy'),
  ('bytes', 'Easy'),
  ('cent', 'Easy'),
  ('fight', 'Easy'),
  ('height', 'Medium'),
  ('null', 'Easy'),
  ('zero', 'Easy'),
  ('speaker', 'Medium'),
  ('offices', 'Medium'),
  ('roll', 'Easy'),
  ('secret', 'Medium'),
  ('bath', 'Easy'),
  ('injury', 'Medium'),
  ('figures', 'Medium'),
  ('conduct', 'Medium'),
  ('profiles', 'Challenge'),
  ('houses', 'Medium'),
  ('wear', 'Easy'),
  ('frequency', 'Challenge'),
  ('finish', 'Medium'),
  ('physics', 'Medium'),
  ('samples', 'Medium'),
  ('forecast', 'Challenge'),
  ('cycle', 'Easy'),
  ('accuracy', 'Challenge'),
  ('sleep', 'Easy'),
  ('scene', 'Easy'),
  ('crystal', 'Medium'),
  ('writer', 'Medium'),
  ('chairman', 'Challenge'),
  ('drink', 'Easy'),
  ('seat', 'Easy'),
  ('vendor', 'Medium'),
  ('regulation', 'Challenge'),
  ('reduction', 'Challenge'),
  ('recording', 'Challenge'),
  ('cape', 'Easy'),
  ('meaning', 'Medium'),
  ('mine', 'Easy'),
  ('henry', 'Easy'),
  ('ticket', 'Medium'),
  ('guess', 'Easy'),
  ('prevention', 'Challenge'),
  ('math', 'Easy'),
  ('presence', 'Challenge'),
  ('majority', 'Challenge'),
  ('moon', 'Easy'),
  ('utility', 'Medium'),
  ('manner', 'Medium'),
  ('strength', 'Challenge'),
  ('degrees', 'Medium')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'password', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'password'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('fear', 'Easy'),
  ('convention', 'Challenge'),
  ('shares', 'Medium'),
  ('principal', 'Challenge'),
  ('daughter', 'Challenge'),
  ('standing', 'Challenge'),
  ('comfort', 'Medium'),
  ('appeal', 'Medium'),
  ('cruise', 'Medium'),
  ('beat', 'Easy'),
  ('drives', 'Medium'),
  ('trees', 'Easy'),
  ('dress', 'Easy'),
  ('dealer', 'Medium'),
  ('exposure', 'Challenge'),
  ('signature', 'Challenge'),
  ('provision', 'Challenge'),
  ('frames', 'Medium'),
  ('circuit', 'Medium'),
  ('layer', 'Easy'),
  ('removal', 'Medium'),
  ('spot', 'Easy'),
  ('factory', 'Medium'),
  ('interior', 'Challenge'),
  ('americans', 'Challenge'),
  ('promotion', 'Challenge'),
  ('clock', 'Easy'),
  ('conversion', 'Challenge'),
  ('feeling', 'Medium'),
  ('serial', 'Medium'),
  ('relief', 'Medium'),
  ('revision', 'Challenge'),
  ('influence', 'Challenge'),
  ('ratio', 'Easy'),
  ('importance', 'Challenge'),
  ('rain', 'Easy'),
  ('permit', 'Medium'),
  ('proof', 'Easy'),
  ('instance', 'Challenge'),
  ('hole', 'Easy'),
  ('ride', 'Easy'),
  ('bureau', 'Medium'),
  ('pair', 'Easy'),
  ('ideal', 'Easy'),
  ('pieces', 'Medium'),
  ('stress', 'Medium'),
  ('shape', 'Easy'),
  ('objectives', 'Challenge'),
  ('remains', 'Medium'),
  ('operator', 'Challenge'),
  ('structures', 'Challenge'),
  ('usage', 'Easy'),
  ('peak', 'Easy'),
  ('wheel', 'Easy'),
  ('transit', 'Medium'),
  ('salt', 'Easy'),
  ('bell', 'Easy'),
  ('attempt', 'Medium'),
  ('accordance', 'Challenge'),
  ('width', 'Easy'),
  ('noise', 'Easy'),
  ('engines', 'Medium'),
  ('array', 'Easy'),
  ('alcohol', 'Medium'),
  ('sister', 'Medium'),
  ('extent', 'Medium'),
  ('lane', 'Easy'),
  ('paragraph', 'Challenge'),
  ('kill', 'Easy'),
  ('aircraft', 'Challenge'),
  ('modules', 'Medium'),
  ('conflict', 'Challenge'),
  ('percentage', 'Challenge'),
  ('concern', 'Medium'),
  ('backup', 'Medium'),
  ('trouble', 'Medium'),
  ('ages', 'Easy'),
  ('plug', 'Easy'),
  ('specialist', 'Challenge'),
  ('plate', 'Easy'),
  ('expenses', 'Challenge'),
  ('indicate', 'Challenge'),
  ('diseases', 'Challenge'),
  ('equivalent', 'Challenge'),
  ('chemistry', 'Challenge'),
  ('variables', 'Challenge'),
  ('logic', 'Easy'),
  ('circle', 'Medium'),
  ('soil', 'Easy'),
  ('responses', 'Challenge'),
  ('leaving', 'Medium'),
  ('sizes', 'Easy'),
  ('exit', 'Easy'),
  ('launch', 'Medium'),
  ('wave', 'Easy'),
  ('guidance', 'Challenge'),
  ('trail', 'Easy'),
  ('symbol', 'Medium'),
  ('highway', 'Medium'),
  ('setup', 'Easy')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'password', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'password'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt, category) AS (VALUES
  ('poll', 'Easy'),
  ('glossary', 'Challenge'),
  ('bond', 'Easy'),
  ('portion', 'Medium'),
  ('scope', 'Easy'),
  ('cables', 'Medium'),
  ('cotton', 'Medium'),
  ('causes', 'Medium'),
  ('retirement', 'Challenge'),
  ('scores', 'Medium'),
  ('efficiency', 'Challenge'),
  ('commitment', 'Challenge'),
  ('specialty', 'Challenge'),
  ('carrier', 'Medium'),
  ('mouth', 'Easy'),
  ('meter', 'Easy'),
  ('wonder', 'Medium'),
  ('fruit', 'Easy'),
  ('lens', 'Easy'),
  ('discovery', 'Challenge'),
  ('confidence', 'Challenge'),
  ('leaves', 'Medium'),
  ('engineer', 'Challenge'),
  ('clearance', 'Challenge'),
  ('inventory', 'Challenge'),
  ('objective', 'Challenge'),
  ('sugar', 'Easy'),
  ('crew', 'Easy'),
  ('stick', 'Easy'),
  ('relation', 'Challenge'),
  ('slide', 'Easy'),
  ('rear', 'Easy'),
  ('parameter', 'Challenge'),
  ('processor', 'Challenge'),
  ('lock', 'Easy'),
  ('storm', 'Easy'),
  ('colleges', 'Challenge'),
  ('mile', 'Easy'),
  ('challenges', 'Challenge'),
  ('bowl', 'Easy'),
  ('tank', 'Easy'),
  ('submission', 'Challenge'),
  ('navy', 'Easy'),
  ('inspection', 'Challenge'),
  ('paint', 'Easy'),
  ('delay', 'Easy'),
  ('pilot', 'Easy'),
  ('outlet', 'Medium'),
  ('execution', 'Challenge'),
  ('disability', 'Challenge'),
  ('increases', 'Challenge'),
  ('dish', 'Easy'),
  ('painting', 'Challenge'),
  ('universe', 'Challenge'),
  ('candidate', 'Challenge'),
  ('slot', 'Easy'),
  ('messenger', 'Challenge'),
  ('mirror', 'Medium'),
  ('hate', 'Easy'),
  ('rice', 'Easy'),
  ('loop', 'Easy'),
  ('guard', 'Easy'),
  ('saving', 'Medium'),
  ('raise', 'Easy'),
  ('expansion', 'Challenge'),
  ('tomorrow', 'Challenge'),
  ('milk', 'Easy'),
  ('keyboard', 'Challenge'),
  ('boot', 'Easy'),
  ('audit', 'Easy'),
  ('push', 'Easy'),
  ('chamber', 'Medium'),
  ('muscle', 'Medium'),
  ('implement', 'Challenge'),
  ('tower', 'Easy'),
  ('calculator', 'Challenge'),
  ('shower', 'Medium'),
  ('shell', 'Easy'),
  ('governor', 'Challenge'),
  ('formula', 'Medium'),
  ('catch', 'Easy'),
  ('doubt', 'Easy'),
  ('classroom', 'Challenge'),
  ('democracy', 'Challenge'),
  ('resistance', 'Challenge'),
  ('visitor', 'Medium'),
  ('twin', 'Easy'),
  ('candidates', 'Challenge'),
  ('fighting', 'Challenge'),
  ('instrument', 'Challenge'),
  ('suit', 'Easy'),
  ('shift', 'Easy'),
  ('chip', 'Easy'),
  ('choices', 'Medium'),
  ('carbon', 'Medium'),
  ('header', 'Medium'),
  ('echo', 'Easy'),
  ('grid', 'Easy'),
  ('revolution', 'Challenge'),
  ('journey', 'Medium')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'password', seed.prompt, seed.prompt, seed.category, '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'password'
    AND existing.`owner_room_id` IS NULL
    AND lower(trim(existing.`prompt`)) = lower(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt) AS (VALUES
  ('IN'),
  ('ER'),
  ('ON'),
  ('RE'),
  ('TI'),
  ('ES'),
  ('EN'),
  ('TE'),
  ('AT'),
  ('NG'),
  ('ED'),
  ('AN'),
  ('NT'),
  ('ST'),
  ('AL'),
  ('AR'),
  ('IO'),
  ('OR'),
  ('CO'),
  ('RA'),
  ('LE'),
  ('RI'),
  ('DE'),
  ('SE'),
  ('IC'),
  ('LI'),
  ('IT'),
  ('IS'),
  ('NS'),
  ('ME'),
  ('VE'),
  ('RO'),
  ('EA'),
  ('CE'),
  ('NE'),
  ('LA'),
  ('EL'),
  ('DI'),
  ('TA'),
  ('CA'),
  ('SI'),
  ('TR'),
  ('ND'),
  ('EC'),
  ('CH'),
  ('CT'),
  ('AC'),
  ('RS'),
  ('PE'),
  ('PR'),
  ('LL'),
  ('AS'),
  ('UR'),
  ('TO'),
  ('MA'),
  ('HE'),
  ('OL'),
  ('TS'),
  ('OU'),
  ('IE'),
  ('TH'),
  ('LO'),
  ('IL'),
  ('NI'),
  ('OM'),
  ('SS'),
  ('ET'),
  ('NC'),
  ('NA'),
  ('RT'),
  ('MI'),
  ('GE'),
  ('IA'),
  ('HO'),
  ('PA'),
  ('PO'),
  ('HA'),
  ('UN'),
  ('AD'),
  ('EM'),
  ('LY'),
  ('SH'),
  ('AI'),
  ('AM'),
  ('SU'),
  ('US'),
  ('VI'),
  ('FI'),
  ('SO'),
  ('HI'),
  ('MO'),
  ('OT'),
  ('PL'),
  ('MP'),
  ('UT'),
  ('CI'),
  ('ID'),
  ('IV'),
  ('TU'),
  ('EE')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'bomb', seed.prompt, NULL, 'Letter pair', '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'bomb'
    AND existing.`owner_room_id` IS NULL
    AND upper(trim(existing.`prompt`)) = upper(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt) AS (VALUES
  ('AP'),
  ('BE'),
  ('RY'),
  ('OS'),
  ('SP'),
  ('KE'),
  ('IM'),
  ('IR'),
  ('OO'),
  ('OP'),
  ('CK'),
  ('IG'),
  ('TY'),
  ('BL'),
  ('DA'),
  ('AB'),
  ('UL'),
  ('CR'),
  ('SC'),
  ('FO'),
  ('TT'),
  ('FE'),
  ('GR'),
  ('AG'),
  ('BA'),
  ('CL'),
  ('RD'),
  ('OC'),
  ('OW'),
  ('WA'),
  ('BO'),
  ('NO'),
  ('SA'),
  ('BI'),
  ('EP'),
  ('DS'),
  ('EV'),
  ('PI'),
  ('CU'),
  ('OD'),
  ('IP'),
  ('UM'),
  ('BR'),
  ('GA'),
  ('RR'),
  ('LS'),
  ('OV'),
  ('WI'),
  ('PP'),
  ('WE'),
  ('RM'),
  ('GI'),
  ('RN'),
  ('AY'),
  ('RU'),
  ('GH'),
  ('LU'),
  ('NN'),
  ('VA'),
  ('BU'),
  ('DO'),
  ('FA'),
  ('UC'),
  ('EG'),
  ('UA'),
  ('EF'),
  ('IF'),
  ('KI'),
  ('PT'),
  ('UE'),
  ('OG'),
  ('IB'),
  ('LD'),
  ('LT'),
  ('UI'),
  ('DU'),
  ('FF'),
  ('AU'),
  ('RC'),
  ('PH'),
  ('EW'),
  ('KS'),
  ('UP'),
  ('RG'),
  ('AV'),
  ('PU'),
  ('HT'),
  ('OB'),
  ('UB'),
  ('DR'),
  ('GU'),
  ('MM'),
  ('PS'),
  ('TL'),
  ('OA'),
  ('CC'),
  ('OK'),
  ('RK'),
  ('WO'),
  ('MB')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'bomb', seed.prompt, NULL, 'Letter pair', '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'bomb'
    AND existing.`owner_room_id` IS NULL
    AND upper(trim(existing.`prompt`)) = upper(trim(seed.prompt))
);
--> statement-breakpoint
WITH seed(prompt) AS (VALUES
  ('MS'),
  ('GO'),
  ('GS'),
  ('NU'),
  ('UG'),
  ('FL'),
  ('UD'),
  ('VO'),
  ('FR'),
  ('RL'),
  ('AK'),
  ('FU'),
  ('RV'),
  ('YS'),
  ('GN'),
  ('HU'),
  ('NK'),
  ('NV'),
  ('BS'),
  ('SL'),
  ('EY'),
  ('EI'),
  ('OF'),
  ('NF'),
  ('CS'),
  ('EB'),
  ('HR'),
  ('NY'),
  ('OI'),
  ('AF'),
  ('MU'),
  ('SK'),
  ('YE'),
  ('DD'),
  ('GL'),
  ('CY'),
  ('DY'),
  ('TC'),
  ('SY'),
  ('RP'),
  ('WH'),
  ('EO'),
  ('SM'),
  ('WS'),
  ('AW'),
  ('OY'),
  ('WN'),
  ('DV'),
  ('SW'),
  ('DL'),
  ('NL'),
  ('FT'),
  ('GG'),
  ('LV'),
  ('RF'),
  ('KA'),
  ('YO'),
  ('DG'),
  ('IK'),
  ('LK'),
  ('YI'),
  ('YM'),
  ('HY'),
  ('LF'),
  ('TW'),
  ('EU'),
  ('GY'),
  ('RB'),
  ('TM'),
  ('EH'),
  ('HN'),
  ('MY'),
  ('EK'),
  ('KN'),
  ('LP'),
  ('YL'),
  ('DM'),
  ('IU'),
  ('UF'),
  ('WR'),
  ('YN'),
  ('NM'),
  ('OE'),
  ('AH'),
  ('BY'),
  ('LC'),
  ('SF'),
  ('TN'),
  ('YC'),
  ('BB'),
  ('HL'),
  ('KL'),
  ('KO'),
  ('LB'),
  ('PY'),
  ('YA'),
  ('YB'),
  ('YP'),
  ('FY'),
  ('GT')
)
INSERT INTO `game_content` (`game_type`,`prompt`,`answer`,`category`,`metadata`,`is_active`,`owner_room_id`)
SELECT 'bomb', seed.prompt, NULL, 'Letter pair', '{}', 1, NULL
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM `game_content` existing
  WHERE existing.`game_type` = 'bomb'
    AND existing.`owner_room_id` IS NULL
    AND upper(trim(existing.`prompt`)) = upper(trim(seed.prompt))
);

