-- Taboo bank v3: retain 55 strong cards and replace 165 cards (75%).
-- Room-specific custom cards and historical records are preserved.

DROP TABLE IF EXISTS `_taboo_v3_seed`;
--> statement-breakpoint
CREATE TABLE `_taboo_v3_seed` (`prompt` text PRIMARY KEY NOT NULL, `category` text NOT NULL, `metadata` text NOT NULL);
--> statement-breakpoint
INSERT INTO `_taboo_v3_seed` (`prompt`, `category`, `metadata`) VALUES
  ('Square', 'Objects & Shapes', '{"taboo":["four","equal","sides","corners","box"]}'),
  ('Circle', 'Objects & Shapes', '{"taboo":["round","shape","ring","ball","centre"]}'),
  ('Triangle', 'Objects & Shapes', '{"taboo":["three","sides","corners","shape","angle"]}'),
  ('Rectangle', 'Objects & Shapes', '{"taboo":["four","sides","long","shape","opposite"]}'),
  ('Pencil', 'Everyday Objects', '{"taboo":["write","draw","eraser","sharpener","lead"]}'),
  ('Eraser', 'Everyday Objects', '{"taboo":["rubber","pencil","mistake","remove","school"]}'),
  ('Scissors', 'Everyday Objects', '{"taboo":["cut","blades","paper","sharp","pair"]}'),
  ('Umbrella', 'Everyday Objects', '{"taboo":["rain","wet","cover","handle","open"]}'),
  ('Mirror', 'Everyday Objects', '{"taboo":["reflection","glass","look","face","image"]}'),
  ('Pillow', 'Everyday Objects', '{"taboo":["sleep","head","bed","soft","cushion"]}'),
  ('Blanket', 'Everyday Objects', '{"taboo":["warm","bed","cover","sleep","cold"]}'),
  ('Toothbrush', 'Everyday Objects', '{"taboo":["teeth","paste","clean","bathroom","bristles"]}'),
  ('Candle', 'Everyday Objects', '{"taboo":["wax","flame","light","burn","wick"]}'),
  ('Clock', 'Everyday Objects', '{"taboo":["time","hours","hands","wall","tick"]}'),
  ('Key', 'Everyday Objects', '{"taboo":["lock","door","open","metal","unlock"]}'),
  ('Wallet', 'Everyday Objects', '{"taboo":["money","cards","pocket","cash","leather"]}'),
  ('Backpack', 'Everyday Objects', '{"taboo":["bag","school","shoulders","carry","zip"]}'),
  ('Ladder', 'Everyday Objects', '{"taboo":["climb","steps","height","roof","rungs"]}'),
  ('Hammer', 'Everyday Objects', '{"taboo":["nail","hit","tool","wood","build"]}'),
  ('Screwdriver', 'Everyday Objects', '{"taboo":["screw","tool","turn","handle","tighten"]}'),
  ('Broom', 'Everyday Objects', '{"taboo":["sweep","floor","clean","dust","bristles"]}'),
  ('Bucket', 'Everyday Objects', '{"taboo":["water","handle","carry","container","plastic"]}'),
  ('Fridge', 'Everyday Objects', '{"taboo":["cold","food","kitchen","freezer","door"]}'),
  ('Microwave', 'Everyday Objects', '{"taboo":["heat","food","kitchen","seconds","oven"]}'),
  ('Kettle', 'Everyday Objects', '{"taboo":["boil","water","tea","hot","kitchen"]}'),
  ('Washing Machine', 'Everyday Objects', '{"taboo":["clothes","laundry","wash","spin","detergent"]}'),
  ('Remote Control', 'Everyday Objects', '{"taboo":["television","buttons","channel","volume","battery"]}'),
  ('Sunglasses', 'Everyday Objects', '{"taboo":["sun","eyes","dark","wear","shades"]}'),
  ('Headphones', 'Everyday Objects', '{"taboo":["music","ears","listen","sound","wireless"]}'),
  ('Camera', 'Everyday Objects', '{"taboo":["photo","picture","lens","take","flash"]}'),
  ('Pizza', 'Food & Drink', '{"taboo":["cheese","slice","toppings","dough","Italian"]}'),
  ('Burger', 'Food & Drink', '{"taboo":["bun","patty","beef","cheese","fast food"]}'),
  ('Sandwich', 'Food & Drink', '{"taboo":["bread","filling","lunch","slices","toast"]}'),
  ('Chocolate', 'Food & Drink', '{"taboo":["sweet","cocoa","bar","brown","dessert"]}'),
  ('Ice Cream', 'Food & Drink', '{"taboo":["cold","scoop","cone","melt","flavour"]}'),
  ('Popcorn', 'Food & Drink', '{"taboo":["cinema","movie","corn","snack","butter"]}'),
  ('Coffee', 'Food & Drink', '{"taboo":["drink","caffeine","beans","cup","morning"]}'),
  ('Tea', 'Food & Drink', '{"taboo":["drink","cup","bag","hot","milk"]}'),
  ('Milk', 'Food & Drink', '{"taboo":["cow","white","drink","cereal","dairy"]}'),
  ('Bread', 'Food & Drink', '{"taboo":["loaf","slice","toast","sandwich","bake"]}'),
  ('Cheese', 'Food & Drink', '{"taboo":["dairy","milk","yellow","slice","melt"]}'),
  ('Egg', 'Food & Drink', '{"taboo":["chicken","shell","yolk","breakfast","boil"]}'),
  ('Banana', 'Food & Drink', '{"taboo":["yellow","fruit","peel","monkey","bunch"]}'),
  ('Apple', 'Food & Drink', '{"taboo":["fruit","red","green","tree","bite"]}'),
  ('Watermelon', 'Food & Drink', '{"taboo":["fruit","green","red","seeds","summer"]}'),
  ('Lemon', 'Food & Drink', '{"taboo":["yellow","sour","fruit","juice","citrus"]}'),
  ('Potato', 'Food & Drink', '{"taboo":["chips","vegetable","mash","peel","starch"]}'),
  ('Rice', 'Food & Drink', '{"taboo":["grain","white","cook","bowl","staple"]}'),
  ('Pasta', 'Food & Drink', '{"taboo":["Italian","noodles","sauce","spaghetti","boil"]}'),
  ('Soup', 'Food & Drink', '{"taboo":["bowl","liquid","hot","spoon","broth"]}'),
  ('Salad', 'Food & Drink', '{"taboo":["lettuce","healthy","vegetables","bowl","dressing"]}'),
  ('Cake', 'Food & Drink', '{"taboo":["birthday","icing","bake","slice","candles"]}'),
  ('Doughnut', 'Food & Drink', '{"taboo":["round","hole","sweet","fried","icing"]}'),
  ('Biscuit', 'Food & Drink', '{"taboo":["cookie","crunchy","tea","snack","bake"]}'),
  ('Honey', 'Food & Drink', '{"taboo":["bee","sweet","sticky","hive","golden"]}'),
  ('Dentist', 'People & Jobs', '{"taboo":["teeth","mouth","doctor","drill","cavity"]}'),
  ('Barber', 'People & Jobs', '{"taboo":["hair","cut","clippers","salon","shave"]}'),
  ('Waiter', 'People & Jobs', '{"taboo":["restaurant","food","serve","table","tip"]}'),
  ('Lawyer', 'People & Jobs', '{"taboo":["court","law","judge","case","client"]}'),
  ('Cashier', 'People & Jobs', '{"taboo":["money","till","shop","pay","receipt"]}'),
  ('Photographer', 'People & Jobs', '{"taboo":["camera","pictures","photos","lens","shoot"]}'),
  ('Plumber', 'People & Jobs', '{"taboo":["pipes","water","toilet","leak","repair"]}'),
  ('Electrician', 'People & Jobs', '{"taboo":["wires","power","electricity","plug","repair"]}'),
  ('Journalist', 'People & Jobs', '{"taboo":["news","report","story","newspaper","interview"]}'),
  ('Actor', 'People & Jobs', '{"taboo":["movie","play","character","stage","perform"]}'),
  ('DJ', 'People & Jobs', '{"taboo":["music","songs","club","mix","turntable"]}'),
  ('Referee', 'People & Jobs', '{"taboo":["game","whistle","rules","sport","official"]}'),
  ('Architect', 'People & Jobs', '{"taboo":["building","design","plans","draw","house"]}'),
  ('Security Guard', 'People & Jobs', '{"taboo":["protect","uniform","gate","watch","safety"]}'),
  ('Delivery Driver', 'People & Jobs', '{"taboo":["package","door","van","order","bring"]}'),
  ('Hospital', 'Places', '{"taboo":["doctor","nurse","patient","sick","medicine"]}'),
  ('Airport', 'Places', '{"taboo":["plane","flight","travel","passport","terminal"]}'),
  ('Library', 'Places', '{"taboo":["books","read","quiet","borrow","shelves"]}'),
  ('Restaurant', 'Places', '{"taboo":["food","eat","waiter","menu","table"]}'),
  ('Cinema', 'Places', '{"taboo":["movie","screen","popcorn","film","tickets"]}'),
  ('Beach', 'Places', '{"taboo":["sand","sea","ocean","swim","waves"]}'),
  ('Museum', 'Places', '{"taboo":["history","art","exhibits","old","visit"]}'),
  ('Stadium', 'Places', '{"taboo":["sport","crowd","seats","field","match"]}'),
  ('Supermarket', 'Places', '{"taboo":["shop","groceries","food","trolley","aisles"]}'),
  ('Pharmacy', 'Places', '{"taboo":["medicine","pills","chemist","prescription","health"]}'),
  ('Gym', 'Places', '{"taboo":["exercise","weights","fitness","workout","muscles"]}'),
  ('Church', 'Places', '{"taboo":["pray","religion","Sunday","pastor","worship"]}'),
  ('Hotel', 'Places', '{"taboo":["room","sleep","holiday","reception","guest"]}'),
  ('Prison', 'Places', '{"taboo":["jail","criminal","bars","cell","sentence"]}'),
  ('Playground', 'Places', '{"taboo":["children","swings","slide","park","play"]}'),
  ('Lion', 'Animals', '{"taboo":["king","jungle","roar","mane","cat"]}'),
  ('Elephant', 'Animals', '{"taboo":["trunk","tusks","grey","large","animal"]}'),
  ('Giraffe', 'Animals', '{"taboo":["tall","neck","spots","Africa","animal"]}'),
  ('Penguin', 'Animals', '{"taboo":["black","white","ice","bird","waddle"]}'),
  ('Dolphin', 'Animals', '{"taboo":["ocean","swim","intelligent","fin","mammal"]}'),
  ('Shark', 'Animals', '{"taboo":["ocean","teeth","fin","dangerous","fish"]}'),
  ('Crocodile', 'Animals', '{"taboo":["teeth","river","reptile","water","alligator"]}'),
  ('Monkey', 'Animals', '{"taboo":["banana","tree","ape","climb","tail"]}'),
  ('Kangaroo', 'Animals', '{"taboo":["Australia","jump","pouch","baby","hop"]}'),
  ('Owl', 'Animals', '{"taboo":["night","bird","eyes","hoot","wise"]}'),
  ('Snake', 'Animals', '{"taboo":["slither","bite","venom","reptile","long"]}'),
  ('Spider', 'Animals', '{"taboo":["eight","legs","web","insect","bite"]}'),
  ('Butterfly', 'Animals', '{"taboo":["wings","colourful","caterpillar","fly","insect"]}'),
  ('Frog', 'Animals', '{"taboo":["jump","green","pond","croak","tadpole"]}'),
  ('Zebra', 'Animals', '{"taboo":["stripes","black","white","horse","Africa"]}'),
  ('Rainbow', 'Nature & Weather', '{"taboo":["colours","rain","sky","arc","sun"]}'),
  ('Thunder', 'Nature & Weather', '{"taboo":["storm","lightning","loud","sky","sound"]}'),
  ('Lightning', 'Nature & Weather', '{"taboo":["thunder","flash","storm","sky","electric"]}'),
  ('Tornado', 'Nature & Weather', '{"taboo":["wind","funnel","storm","spin","destroy"]}'),
  ('Snow', 'Nature & Weather', '{"taboo":["white","cold","winter","ice","flakes"]}'),
  ('Desert', 'Nature & Weather', '{"taboo":["sand","hot","dry","camel","water"]}'),
  ('Volcano', 'Nature & Weather', '{"taboo":["lava","eruption","mountain","hot","ash"]}'),
  ('Earthquake', 'Nature & Weather', '{"taboo":["ground","shake","buildings","magnitude","tremor"]}'),
  ('Waterfall', 'Nature & Weather', '{"taboo":["water","river","drop","cliff","flow"]}'),
  ('Island', 'Nature & Weather', '{"taboo":["water","ocean","land","beach","surrounded"]}'),
  ('Forest', 'Nature & Weather', '{"taboo":["trees","woods","animals","green","nature"]}'),
  ('Moon', 'Nature & Weather', '{"taboo":["night","sky","space","round","Earth"]}'),
  ('Sunrise', 'Nature & Weather', '{"taboo":["morning","sun","east","dawn","light"]}'),
  ('Shadow', 'Nature & Weather', '{"taboo":["light","dark","shape","sun","follow"]}'),
  ('Cloud', 'Nature & Weather', '{"taboo":["sky","white","rain","weather","fluffy"]}'),
  ('Homework', 'School & Technology', '{"taboo":["school","teacher","study","assignment","home"]}'),
  ('Calculator', 'School & Technology', '{"taboo":["maths","numbers","add","buttons","calculate"]}'),
  ('Dictionary', 'School & Technology', '{"taboo":["words","meaning","book","definition","alphabet"]}'),
  ('Exam', 'School & Technology', '{"taboo":["test","study","questions","school","marks"]}'),
  ('Graduation', 'School & Technology', '{"taboo":["degree","university","cap","gown","ceremony"]}'),
  ('Laptop', 'School & Technology', '{"taboo":["computer","screen","keyboard","portable","work"]}'),
  ('Internet', 'School & Technology', '{"taboo":["online","web","Wi-Fi","browser","connect"]}'),
  ('Password', 'School & Technology', '{"taboo":["login","secret","account","characters","access"]}'),
  ('Email', 'School & Technology', '{"taboo":["message","send","inbox","address","online"]}'),
  ('Screenshot', 'School & Technology', '{"taboo":["screen","picture","capture","phone","image"]}'),
  ('Keyboard', 'School & Technology', '{"taboo":["type","computer","keys","letters","spacebar"]}'),
  ('Charger', 'School & Technology', '{"taboo":["battery","phone","power","cable","plug"]}'),
  ('Wi-Fi', 'School & Technology', '{"taboo":["internet","wireless","router","password","connect"]}'),
  ('Robot', 'School & Technology', '{"taboo":["machine","human","automatic","metal","program"]}'),
  ('Artificial Intelligence', 'School & Technology', '{"taboo":["AI","computer","ChatGPT","machine","smart"]}'),
  ('Concert', 'Entertainment', '{"taboo":["music","live","singer","stage","crowd"]}'),
  ('Podcast', 'Entertainment', '{"taboo":["listen","audio","episode","host","talk"]}'),
  ('Karaoke', 'Entertainment', '{"taboo":["sing","microphone","lyrics","music","bar"]}'),
  ('Cartoon', 'Entertainment', '{"taboo":["animated","children","drawings","television","character"]}'),
  ('Comedy', 'Entertainment', '{"taboo":["funny","laugh","jokes","stand-up","humour"]}'),
  ('Horror Movie', 'Entertainment', '{"taboo":["scary","film","ghost","scream","fear"]}'),
  ('Reality Show', 'Entertainment', '{"taboo":["television","real","contestants","drama","camera"]}'),
  ('Video Game', 'Entertainment', '{"taboo":["play","console","controller","screen","gaming"]}'),
  ('Board Game', 'Entertainment', '{"taboo":["dice","pieces","table","players","rules"]}'),
  ('Magic Trick', 'Entertainment', '{"taboo":["magician","illusion","cards","disappear","rabbit"]}'),
  ('Celebrity', 'Entertainment', '{"taboo":["famous","star","actor","singer","public"]}'),
  ('Superhero', 'Entertainment', '{"taboo":["powers","cape","save","villain","comic"]}'),
  ('Documentary', 'Entertainment', '{"taboo":["facts","film","real","educational","nature"]}'),
  ('Playlist', 'Entertainment', '{"taboo":["songs","music","list","Spotify","listen"]}'),
  ('Dance Challenge', 'Entertainment', '{"taboo":["TikTok","moves","music","trend","video"]}'),
  ('Football', 'Sports', '{"taboo":["ball","goal","kick","soccer","team"]}'),
  ('Basketball', 'Sports', '{"taboo":["ball","hoop","dribble","court","shoot"]}'),
  ('Rugby', 'Sports', '{"taboo":["ball","tackle","scrum","try","team"]}'),
  ('Cricket', 'Sports', '{"taboo":["bat","ball","wicket","bowler","runs"]}'),
  ('Tennis', 'Sports', '{"taboo":["racket","ball","court","net","serve"]}'),
  ('Swimming', 'Sports', '{"taboo":["water","pool","stroke","race","swim"]}'),
  ('Boxing', 'Sports', '{"taboo":["fight","gloves","ring","punch","round"]}'),
  ('Marathon', 'Sports', '{"taboo":["run","race","long","kilometres","runner"]}'),
  ('Golf', 'Sports', '{"taboo":["club","ball","hole","course","swing"]}'),
  ('Cycling', 'Sports', '{"taboo":["bicycle","ride","pedal","helmet","race"]}'),
  ('Gymnastics', 'Sports', '{"taboo":["flip","balance","floor","flexible","routine"]}'),
  ('Wrestling', 'Sports', '{"taboo":["fight","ring","pin","grapple","opponent"]}'),
  ('Skateboard', 'Sports', '{"taboo":["board","wheels","trick","ride","ramp"]}'),
  ('Penalty', 'Sports', '{"taboo":["foul","kick","referee","punishment","goal"]}'),
  ('Trophy', 'Sports', '{"taboo":["winner","cup","prize","award","champion"]}'),
  ('Whisper', 'Actions & Feelings', '{"taboo":["quiet","speak","soft","secret","voice"]}'),
  ('Sneeze', 'Actions & Feelings', '{"taboo":["nose","achoo","tissue","cold","allergy"]}'),
  ('Laugh', 'Actions & Feelings', '{"taboo":["funny","smile","joke","sound","happy"]}'),
  ('Cry', 'Actions & Feelings', '{"taboo":["tears","sad","eyes","upset","weep"]}'),
  ('Yawn', 'Actions & Feelings', '{"taboo":["tired","mouth","sleep","open","bored"]}'),
  ('Hug', 'Actions & Feelings', '{"taboo":["arms","embrace","love","hold","person"]}'),
  ('Jealous', 'Actions & Feelings', '{"taboo":["envy","want","possessive","relationship","green"]}'),
  ('Embarrassed', 'Actions & Feelings', '{"taboo":["ashamed","red","awkward","mistake","shy"]}'),
  ('Confused', 'Actions & Feelings', '{"taboo":["understand","lost","puzzled","unsure","question"]}'),
  ('Excited', 'Actions & Feelings', '{"taboo":["happy","eager","energy","cannot wait","thrilled"]}'),
  ('Bored', 'Actions & Feelings', '{"taboo":["nothing","tired","uninterested","dull","yawn"]}'),
  ('Apologise', 'Actions & Feelings', '{"taboo":["sorry","forgive","mistake","regret","excuse"]}'),
  ('Celebrate', 'Actions & Feelings', '{"taboo":["party","win","happy","occasion","cheer"]}'),
  ('Complain', 'Actions & Feelings', '{"taboo":["problem","unhappy","service","moan","manager"]}'),
  ('Promise', 'Actions & Feelings', '{"taboo":["keep","word","swear","commit","break"]}'),
  ('Load Shedding', 'South Africa', '{"taboo":["Eskom","electricity","power","outage","lights"]}'),
  ('Springboks', 'South Africa', '{"taboo":["rugby","green","gold","national","team"]}'),
  ('Bafana Bafana', 'South Africa', '{"taboo":["football","national","team","soccer","yellow"]}'),
  ('Amapiano', 'South Africa', '{"taboo":["music","piano","dance","South Africa","log drum"]}'),
  ('Traffic Robot', 'South African English', '{"taboo":["traffic light","road","red","green","intersection"]}'),
  ('Tekkies', 'South African English', '{"taboo":["shoes","sneakers","feet","trainers","wear"]}'),
  ('Bakkie', 'South African English', '{"taboo":["vehicle","truck","load","drive","pickup"]}'),
  ('Spaza Shop', 'South Africa', '{"taboo":["township","small","store","buy","groceries"]}'),
  ('Shebeen', 'South Africa', '{"taboo":["tavern","drink","township","bar","alcohol"]}'),
  ('Gogo', 'South Africa', '{"taboo":["grandmother","old","family","woman","granny"]}'),
  ('Mzansi Magic', 'South Africa', '{"taboo":["television","channel","DStv","shows","drama"]}'),
  ('Union Buildings', 'South Africa', '{"taboo":["Pretoria","government","president","landmark","office"]}'),
  ('Robben Island', 'South Africa', '{"taboo":["Mandela","prison","Cape Town","ferry","history"]}'),
  ('Blyde River Canyon', 'South Africa', '{"taboo":["Mpumalanga","mountains","view","nature","canyon"]}'),
  ('Comrades Marathon', 'South Africa', '{"taboo":["run","Durban","Pietermaritzburg","race","ultra"]}'),
  ('Passport', 'Travel', '{"taboo":["travel","country","document","airport","stamp"]}'),
  ('Suitcase', 'Travel', '{"taboo":["clothes","travel","pack","luggage","trip"]}'),
  ('Map', 'Travel', '{"taboo":["directions","location","road","navigate","country"]}'),
  ('Traffic Jam', 'Travel', '{"taboo":["cars","road","slow","stuck","rush hour"]}'),
  ('Seatbelt', 'Travel', '{"taboo":["car","safety","strap","wear","buckle"]}'),
  ('Petrol Station', 'Travel', '{"taboo":["fuel","car","gas","fill","pump"]}'),
  ('Taxi', 'Travel', '{"taboo":["driver","ride","fare","transport","car"]}'),
  ('Train', 'Travel', '{"taboo":["railway","station","tracks","carriage","transport"]}'),
  ('Cruise Ship', 'Travel', '{"taboo":["ocean","boat","holiday","passengers","travel"]}'),
  ('Tourist', 'Travel', '{"taboo":["visitor","travel","camera","holiday","sightseeing"]}'),
  ('Road Trip', 'Travel', '{"taboo":["car","drive","long","friends","journey"]}'),
  ('Boarding Pass', 'Travel', '{"taboo":["flight","plane","airport","seat","ticket"]}'),
  ('Window Seat', 'Travel', '{"taboo":["plane","view","aisle","sit","flight"]}'),
  ('Destination', 'Travel', '{"taboo":["place","travel","going","arrival","journey"]}'),
  ('Directions', 'Travel', '{"taboo":["left","right","map","where","route"]}'),
  ('Birthday', 'Events & Relationships', '{"taboo":["cake","candles","party","age","celebrate"]}'),
  ('Wedding', 'Events & Relationships', '{"taboo":["bride","groom","marriage","ring","ceremony"]}'),
  ('Funeral', 'Events & Relationships', '{"taboo":["death","bury","coffin","sad","mourning"]}'),
  ('Baby Shower', 'Events & Relationships', '{"taboo":["pregnant","gifts","mother","baby","party"]}'),
  ('Anniversary', 'Events & Relationships', '{"taboo":["year","couple","marriage","date","celebrate"]}'),
  ('First Date', 'Events & Relationships', '{"taboo":["romantic","meet","restaurant","couple","nervous"]}'),
  ('Breakup', 'Events & Relationships', '{"taboo":["relationship","end","couple","separate","heartbroken"]}'),
  ('Best Friend', 'Events & Relationships', '{"taboo":["close","person","trust","friendship","together"]}'),
  ('Neighbour', 'Events & Relationships', '{"taboo":["next door","house","live","street","person"]}'),
  ('Family Reunion', 'Events & Relationships', '{"taboo":["relatives","gather","home","together","meet"]}'),
  ('Surprise Party', 'Events & Relationships', '{"taboo":["secret","birthday","hide","unexpected","celebrate"]}'),
  ('Invitation', 'Events & Relationships', '{"taboo":["event","come","card","guest","RSVP"]}'),
  ('Gift', 'Events & Relationships', '{"taboo":["present","give","birthday","wrap","surprise"]}'),
  ('Argument', 'Events & Relationships', '{"taboo":["fight","disagree","shout","angry","couple"]}'),
  ('Secret', 'Events & Relationships', '{"taboo":["tell","private","hide","know","share"]}');
--> statement-breakpoint
UPDATE `game_content` SET `is_active` = 0 WHERE `game_type` = 'taboo' AND `owner_room_id` IS NULL;
--> statement-breakpoint
UPDATE `game_content`
SET
  `category` = (SELECT seed.`category` FROM `_taboo_v3_seed` seed WHERE lower(trim(seed.`prompt`)) = lower(trim(`game_content`.`prompt`))),
  `metadata` = (SELECT seed.`metadata` FROM `_taboo_v3_seed` seed WHERE lower(trim(seed.`prompt`)) = lower(trim(`game_content`.`prompt`))),
  `answer` = NULL,
  `is_active` = 1
WHERE `game_type` = 'taboo' AND `owner_room_id` IS NULL
  AND `id` = (SELECT min(existing.`id`) FROM `game_content` existing WHERE existing.`game_type` = 'taboo' AND existing.`owner_room_id` IS NULL AND lower(trim(existing.`prompt`)) = lower(trim(`game_content`.`prompt`)))
  AND EXISTS (SELECT 1 FROM `_taboo_v3_seed` seed WHERE lower(trim(seed.`prompt`)) = lower(trim(`game_content`.`prompt`)));
--> statement-breakpoint
INSERT INTO `game_content` (`game_type`, `prompt`, `answer`, `category`, `metadata`, `is_active`, `owner_room_id`)
SELECT 'taboo', seed.`prompt`, NULL, seed.`category`, seed.`metadata`, 1, NULL
FROM `_taboo_v3_seed` seed
WHERE NOT EXISTS (SELECT 1 FROM `game_content` existing WHERE existing.`game_type` = 'taboo' AND existing.`owner_room_id` IS NULL AND lower(trim(existing.`prompt`)) = lower(trim(seed.`prompt`)));
--> statement-breakpoint
DROP TABLE `_taboo_v3_seed`;
