export type FifthGraderCard = readonly [
  category: string,
  prompt: string,
  answer: string,
];

// Additional non-maths questions used to balance the original maths-heavy bank.
// Questions are intentionally short, host-readable and suitable for spoken play.
export const FIFTH_GRADER_BANK_V2: readonly FifthGraderCard[] = [
  // Natural Science (20)
  ["Natural Science", "Which planet is known as the Red Planet?", "Mars"],
  ["Natural Science", "What is the largest planet in our solar system?", "Jupiter"],
  ["Natural Science", "What is Earth's natural satellite called?", "The Moon"],
  ["Natural Science", "Which organ pumps blood around the human body?", "The heart"],
  ["Natural Science", "Which organs help humans breathe?", "The lungs"],
  ["Natural Science", "What do we call an animal that eats only plants?", "A herbivore"],
  ["Natural Science", "What do we call an animal that eats both plants and meat?", "An omnivore"],
  ["Natural Science", "Which part of a plant absorbs water from the soil?", "The roots"],
  ["Natural Science", "What process do green plants use to make food?", "Photosynthesis"],
  ["Natural Science", "What is the change from a liquid to a gas called?", "Evaporation"],
  ["Natural Science", "What is the change from a gas to a liquid called?", "Condensation"],
  ["Natural Science", "What force pulls objects towards Earth?", "Gravity"],
  ["Natural Science", "What form of energy comes directly from the Sun?", "Solar energy"],
  ["Natural Science", "Which material is usually a good electrical conductor: metal or rubber?", "Metal"],
  ["Natural Science", "What are the three common states of matter?", "Solid, liquid and gas"],
  ["Natural Science", "What do vertebrate animals have that invertebrates do not?", "A backbone"],
  ["Natural Science", "Which blood cells help the body fight infection?", "White blood cells"],
  ["Natural Science", "What protective layer surrounds Earth and contains air?", "The atmosphere"],
  ["Natural Science", "Which simple machine is a sloping surface used to move objects?", "An inclined plane"],
  ["Natural Science", "What do bees collect from flowers to make honey?", "Nectar"],

  // Geography (20)
  ["Geography", "What is the largest continent by land area?", "Asia"],
  ["Geography", "What is the smallest continent by land area?", "Australia"],
  ["Geography", "Which is the largest ocean on Earth?", "The Pacific Ocean"],
  ["Geography", "What imaginary line divides Earth into the Northern and Southern Hemispheres?", "The Equator"],
  ["Geography", "What is land surrounded by water on all sides called?", "An island"],
  ["Geography", "What is a body of land with water on three sides called?", "A peninsula"],
  ["Geography", "What do we call the place where a river begins?", "Its source"],
  ["Geography", "What do we call the place where a river flows into a sea or lake?", "Its mouth"],
  ["Geography", "Which direction is opposite to east?", "West"],
  ["Geography", "What instrument shows direction using a magnetic needle?", "A compass"],
  ["Geography", "What is the capital city of France?", "Paris"],
  ["Geography", "What is the capital city of Kenya?", "Nairobi"],
  ["Geography", "On which continent is Brazil?", "South America"],
  ["Geography", "On which continent is Egypt?", "Africa"],
  ["Geography", "Which desert covers much of northern Africa?", "The Sahara Desert"],
  ["Geography", "What is molten rock called after it reaches Earth's surface?", "Lava"],
  ["Geography", "What is a long period with very little rainfall called?", "A drought"],
  ["Geography", "What map feature explains the meaning of symbols?", "The key or legend"],
  ["Geography", "Which type of map shows countries, provinces and borders?", "A political map"],
  ["Geography", "What are lines running east to west on a globe called?", "Lines of latitude"],

  // History (20)
  ["History", "What do historians call an object made or used by people in the past?", "An artefact"],
  ["History", "What is a written account created during the time being studied called?", "A primary source"],
  ["History", "What ancient civilisation built the pyramids at Giza?", "The ancient Egyptians"],
  ["History", "Which ancient civilisation developed democracy in Athens?", "The ancient Greeks"],
  ["History", "Which city was buried by the eruption of Mount Vesuvius in AD 79?", "Pompeii"],
  ["History", "Who used hieroglyphics as a writing system?", "The ancient Egyptians"],
  ["History", "What was the name of the trade route linking China with Europe?", "The Silk Road"],
  ["History", "Which invention allowed books to be produced much faster in Europe?", "The printing press"],
  ["History", "Who is widely credited with developing the movable-type printing press in Europe?", "Johannes Gutenberg"],
  ["History", "What do we call a period of one hundred years?", "A century"],
  ["History", "How many years are in a decade?", "Ten years"],
  ["History", "Which came first: the Stone Age or the Iron Age?", "The Stone Age"],
  ["History", "What material were Bronze Age tools mainly made from?", "Bronze"],
  ["History", "What do archaeologists study to learn about past societies?", "Physical remains and artefacts"],
  ["History", "What name is given to a person who rules a kingdom?", "A monarch"],
  ["History", "What was the title of a male ruler in ancient Egypt?", "Pharaoh"],
  ["History", "Which civilisation built Machu Picchu?", "The Inca"],
  ["History", "Which ancient people built the Colosseum?", "The Romans"],
  ["History", "What is history passed down by speaking rather than writing called?", "Oral history"],
  ["History", "What name is given to a line showing events in date order?", "A timeline"],

  // English (20)
  ["English", "What part of speech names a person, place, thing or idea?", "A noun"],
  ["English", "What part of speech describes a noun?", "An adjective"],
  ["English", "What part of speech usually describes an action?", "A verb"],
  ["English", "What part of speech describes how an action is done?", "An adverb"],
  ["English", "What is the past tense of 'run'?", "Ran"],
  ["English", "What is the past tense of 'teach'?", "Taught"],
  ["English", "What is the plural of 'analysis'?", "Analyses"],
  ["English", "Give a synonym for 'rapid'.", "Fast or quick"],
  ["English", "Give an antonym for 'scarce'.", "Abundant or plentiful"],
  ["English", "What punctuation mark is used at the end of a direct question?", "A question mark"],
  ["English", "What punctuation mark can show possession?", "An apostrophe"],
  ["English", "What do we call a comparison using 'like' or 'as'?", "A simile"],
  ["English", "What do we call a comparison that says one thing is another?", "A metaphor"],
  ["English", "What is a group of words containing a subject and a verb called?", "A clause"],
  ["English", "What is the collective noun for a group of lions?", "A pride"],
  ["English", "What is the collective noun for a group of fish?", "A school"],
  ["English", "Which word is the pronoun in: 'She opened the door'?", "She"],
  ["English", "Which word is the conjunction in: 'Tea and coffee are available'?", "And"],
  ["English", "What do we call the main character in a story?", "The protagonist"],
  ["English", "What is the setting of a story?", "The time and place where it happens"],

  // Technology (20)
  ["Technology", "What device is used to move a pointer on a computer screen?", "A mouse"],
  ["Technology", "What does a keyboard allow you to enter into a computer?", "Text and commands"],
  ["Technology", "What is a secret code used to protect an account called?", "A password"],
  ["Technology", "What should you do before clicking a suspicious internet link?", "Do not click it; verify the source"],
  ["Technology", "What does it mean to save a copy of data in another location?", "To make a backup"],
  ["Technology", "Which computer part displays pictures and text?", "The monitor or screen"],
  ["Technology", "What is a set of step-by-step instructions called?", "An algorithm"],
  ["Technology", "What do we call an error in a computer program?", "A bug"],
  ["Technology", "What is finding and fixing program errors called?", "Debugging"],
  ["Technology", "Which component supplies electrical energy in a simple circuit?", "A cell or battery"],
  ["Technology", "What must a circuit be for electric current to flow: open or closed?", "Closed"],
  ["Technology", "Which device opens or closes an electrical circuit?", "A switch"],
  ["Technology", "What simple machine consists of a wheel with a grooved rim and a rope?", "A pulley"],
  ["Technology", "What simple machine is a rigid bar that pivots around a point?", "A lever"],
  ["Technology", "What is the pivot point of a lever called?", "The fulcrum"],
  ["Technology", "Why are triangles often used in bridge frames?", "They make the structure rigid and strong"],
  ["Technology", "What property allows a material to bend without breaking?", "Flexibility"],
  ["Technology", "What property describes a material's ability to resist scratching?", "Hardness"],
  ["Technology", "What drawing shows an object as viewed directly from the top?", "A top view or plan view"],
  ["Technology", "What does a prototype allow a designer to do?", "Test and improve a design"],

  // South Africa (20)
  ["South Africa", "What is the legislative capital of South Africa?", "Cape Town"],
  ["South Africa", "What is the administrative capital of South Africa?", "Pretoria"],
  ["South Africa", "What is the judicial capital of South Africa?", "Bloemfontein"],
  ["South Africa", "Which province is Johannesburg in?", "Gauteng"],
  ["South Africa", "Which province is Durban in?", "KwaZulu-Natal"],
  ["South Africa", "Which province is Mbombela in?", "Mpumalanga"],
  ["South Africa", "Which province is Polokwane in?", "Limpopo"],
  ["South Africa", "Which mountain overlooks Cape Town?", "Table Mountain"],
  ["South Africa", "What is South Africa's national flower?", "The king protea"],
  ["South Africa", "What is South Africa's national animal?", "The springbok"],
  ["South Africa", "What is South Africa's national bird?", "The blue crane"],
  ["South Africa", "What is South Africa's national fish?", "The galjoen"],
  ["South Africa", "What is South Africa's national tree?", "The real yellowwood"],
  ["South Africa", "Which two oceans meet near the southern tip of South Africa?", "The Atlantic and Indian Oceans"],
  ["South Africa", "What public holiday is celebrated on 16 June?", "Youth Day"],
  ["South Africa", "What public holiday is celebrated on 24 September?", "Heritage Day"],
  ["South Africa", "Which South African leader received the Nobel Peace Prize with F. W. de Klerk in 1993?", "Nelson Mandela"],
  ["South Africa", "Which famous prison island lies near Cape Town?", "Robben Island"],
  ["South Africa", "Which large national park is found in north-eastern South Africa?", "Kruger National Park"],
  ["South Africa", "What colours are associated with the South African national rugby team?", "Green and gold"],

  // Life Skills (20)
  ["Life Skills", "Which nutrient is the body's main source of energy?", "Carbohydrates"],
  ["Life Skills", "Which nutrient helps build and repair body tissue?", "Protein"],
  ["Life Skills", "Why does the body need water?", "For hydration and normal body functions"],
  ["Life Skills", "What should you do first for a minor burn?", "Cool it under cool running water"],
  ["Life Skills", "What emergency number can be called from a mobile phone in South Africa?", "112"],
  ["Life Skills", "Why should you wash your hands before preparing food?", "To prevent germs from spreading"],
  ["Life Skills", "What protective item should be worn when riding a bicycle?", "A helmet"],
  ["Life Skills", "What should a pedestrian do before crossing a road?", "Stop, look both ways and cross when safe"],
  ["Life Skills", "Which bin should clean paper usually go into?", "A recycling bin"],
  ["Life Skills", "What do the three Rs of waste stand for?", "Reduce, reuse and recycle"],
  ["Life Skills", "Why is regular sleep important?", "It helps the body and brain rest and recover"],
  ["Life Skills", "What should you do if an online stranger asks for personal information?", "Do not share it; tell a trusted adult or report them"],
  ["Life Skills", "What is a balanced diet?", "A diet containing suitable amounts from different food groups"],
  ["Life Skills", "Which habit helps prevent tooth decay?", "Brushing teeth regularly"],
  ["Life Skills", "What is cooperation?", "Working together towards a shared goal"],
  ["Life Skills", "What is empathy?", "Understanding and caring about another person's feelings"],
  ["Life Skills", "What does consent mean?", "Freely agreeing to something"],
  ["Life Skills", "Why should medicine be taken only as directed?", "Incorrect use can be harmful"],
  ["Life Skills", "What should you do if you smell gas indoors?", "Leave, avoid flames or switches, and get help"],
  ["Life Skills", "What is the safest response to lightning outdoors?", "Move to a substantial building or enclosed vehicle"],

  // Arts and Culture (20)
  ["Arts and Culture", "Which three colours are the traditional primary colours in painting?", "Red, yellow and blue"],
  ["Arts and Culture", "What colour is made by mixing blue and yellow paint?", "Green"],
  ["Arts and Culture", "What colour is made by mixing red and blue paint?", "Purple"],
  ["Arts and Culture", "What colour is made by mixing red and yellow paint?", "Orange"],
  ["Arts and Culture", "What do we call a picture an artist makes of themselves?", "A self-portrait"],
  ["Arts and Culture", "What is a three-dimensional artwork made by shaping material called?", "A sculpture"],
  ["Arts and Culture", "What is a repeated decorative design called?", "A pattern"],
  ["Arts and Culture", "What word describes how light or dark a colour is?", "Value or tone"],
  ["Arts and Culture", "How many lines are on a standard musical staff?", "Five"],
  ["Arts and Culture", "What symbol shows silence in written music?", "A rest"],
  ["Arts and Culture", "What word describes the speed of music?", "Tempo"],
  ["Arts and Culture", "What word describes how loud or soft music is?", "Dynamics"],
  ["Arts and Culture", "Which family of instruments does a violin belong to?", "The string family"],
  ["Arts and Culture", "Which family of instruments does a trumpet belong to?", "The brass family"],
  ["Arts and Culture", "What do we call the main tune of a song?", "The melody"],
  ["Arts and Culture", "What do we call a repeated pattern of beats?", "Rhythm"],
  ["Arts and Culture", "What is a person who writes music called?", "A composer"],
  ["Arts and Culture", "What is the written text of a play called?", "A script"],
  ["Arts and Culture", "What do actors do before a performance to practise it?", "Rehearse"],
  ["Arts and Culture", "What is the area where actors perform called?", "The stage"],
];
