const FIVE_ALIVE_GROUPS: Record<string,string[]> = {
  "People": ["Nelson Mandela","Beyoncé","Cristiano Ronaldo","Taylor Swift","Michael Jackson","Rihanna","Lionel Messi","Oprah Winfrey","Usain Bolt","Adele","Drake","Serena Williams","Dwayne Johnson","Trevor Noah","Shakira","LeBron James","Elon Musk","Ed Sheeran","Nicki Minaj","Bruno Mars","MrBeast","Kevin Hart","Will Smith","Snoop Dogg","Eminem","Ariana Grande","Justin Bieber","Kanye West","Bill Gates","Jackie Chan"],
  "Food & Drink": ["Watermelon","Pizza","Sushi","Popcorn","Chocolate","Burger","Pancakes","Ice cream","Spaghetti","Avocado","Coffee","Donut","Tacos","French fries","Cereal","Peanut butter","Hot dog","Cupcake","Cheesecake","Fried chicken","Milkshake","Lasagna","Biltong","Boerewors","Pap","Vetkoek","Curry","Waffles","Nachos","Smoothie"],
  "Animals": ["Giraffe","Penguin","Elephant","Kangaroo","Lion","Dolphin","Crocodile","Flamingo","Gorilla","Zebra","Shark","Octopus","Camel","Peacock","Ostrich","Koala","Panda","Rhinoceros","Hippopotamus","Cheetah","Chameleon","Squirrel","Butterfly","Mosquito","Parrot","Rabbit","Tortoise","Jellyfish","Starfish","Meerkat"],
  "Objects": ["Microwave","Toothbrush","Umbrella","Remote control","Vacuum cleaner","Headphones","Toaster","Laptop","Suitcase","Flashlight","Mirror","Scissors","Stapler","Alarm clock","Shopping trolley","Frying pan","Charger","Backpack","Sunglasses","Hair dryer","Kettle","Bicycle","Hammer","Ladder","Pillow","Calculator","Keyboard","Fan","Doorbell","Water bottle"],
  "Entertainment": ["The Lion King","Titanic","Spider-Man","Harry Potter","SpongeBob SquarePants","Shrek","Frozen","Black Panther","Home Alone","The Simpsons","Barbie","Batman","Superman","The Avengers","Finding Nemo","Toy Story","Jurassic Park","The Matrix","Cinderella","Squid Game","Wednesday","Stranger Things","Fast & Furious","Mission Impossible","The Walking Dead","The Office","Friends","Avatar","The Karate Kid","The Hunger Games"],
  "Places": ["Johannesburg","Cape Town","Durban","Paris","New York City","London","Dubai","Tokyo","Rome","Egypt","Brazil","Australia","Hollywood","Las Vegas","Mount Everest","Sahara Desert","Amazon River","Eiffel Tower","Great Wall of China","Statue of Liberty","Kruger National Park","Table Mountain","Soweto","Pretoria","Limpopo","Hawaii","Antarctica","Disneyland","Times Square","Grand Canyon"],
  "Brands & Tech": ["TikTok","Netflix","YouTube","Instagram","WhatsApp","Google","Apple","Samsung","PlayStation","Xbox","Nike","Adidas","McDonald's","KFC","Coca-Cola","Spotify","Amazon","Facebook","Snapchat","Uber","Toyota","BMW","Mercedes-Benz","Lego","Nintendo","Red Bull","Starbucks","iPhone","ChatGPT","Airbnb"],
  "Sports & Activities": ["Football","Basketball","Rugby","Cricket","Tennis","Swimming","Boxing","Golf","Formula One","Marathon","Skateboarding","Surfing","Volleyball","Gymnastics","Cycling","Fishing","Bowling","Karate","Wrestling","Skiing","Darts","Table tennis","Netball","Hiking","Dancing","Weightlifting","Running","Yoga","Chess","Pool"],
};
export const FIVE_ALIVE_BANK = Object.entries(FIVE_ALIVE_GROUPS).flatMap(([category,items])=>items.map(prompt=>({gameType:"five_alive" as const,prompt,answer:prompt,category,metadata:{difficulty:prompt.length>18?"Medium":"Easy"}})));
