type PhysicalCard={gameType:"charades"|"scavenger"|"bomb";prompt:string;answer:string|null;category:string;metadata:Record<string,unknown>};

const charades=(category:string,items:string[])=>items.map(prompt=>({gameType:"charades" as const,prompt,answer:prompt,category,metadata:{difficulty:prompt.length>22?"Hard":prompt.length>13?"Medium":"Easy",hostNote:"No speaking, mouthing letters, spelling or pointing to written answers."}}));
const scavenger=(category:string,acceptance:string,items:string[])=>items.map(prompt=>({gameType:"scavenger" as const,prompt,answer:null,category,metadata:{acceptance,restrictions:"The item must be physically shown on camera. Pictures displayed on another screen do not count."}}));

const CHARADES:PhysicalCard[]=[
  ...charades("Actions",["Brushing your teeth","Changing a flat tyre","Walking a dog","Opening a stubborn jar","Taking a selfie","Riding a bicycle","Making a sandwich","Catching a fish","Missing the bus","Dancing in the rain","Wrapping a present","Building a snowman","Burning your tongue","Swatting a mosquito","Trying on tight shoes","Blowing up a balloon","Washing a car","Planting a tree","Getting a haircut","Sneaking into a room"]),
  ...charades("Animals",["Penguin","Elephant","Kangaroo","Gorilla","Flamingo","Crocodile","Chicken","Snake","Giraffe","Rabbit","Crab","Frog","Peacock","Ostrich","Shark"]),
  ...charades("Occupations",["Dentist","Firefighter","Photographer","Teacher","Chef","Taxi driver","News reporter","Football referee","Barber","Mechanic","Waiter","Pilot","Police officer","Personal trainer","DJ"]),
  ...charades("Entertainment",["The Lion King","Spider-Man","Titanic","Home Alone","The Matrix","Frozen","Jurassic Park","Mission Impossible","Black Panther","Rocky","Cinderella","The Terminator","Finding Nemo","Harry Potter","The Fast and the Furious"]),
  ...charades("Everyday Life",["Alarm clock","Shopping trolley","Traffic jam","Video call","Power cut","Birthday party","Job interview","First date","Gym workout","Online shopping","Cooking dinner","Watching football","Late for work","Losing your keys","Taking an exam"]),
];

const SCAVENGER:PhysicalCard[]=[
  ...scavenger("Colours","Any safe physical object that clearly matches the requested colour.",["Something blue","Something red","Something green","Something yellow","Something purple","Something orange","Something black","Something white","Something with at least three colours"]),
  ...scavenger("Household","Show the named ordinary household item clearly.",["A spoon","A mug","A pillow","A remote control","A roll of toilet paper","A clothes hanger","A key","A towel","A toothbrush","A frying pan","A light bulb","A charger cable","A laundry basket","A reusable shopping bag","A pair of scissors"]),
  ...scavenger("Clothing","Any wearable item matching the prompt counts.",["Something worn on your head","A sock","A belt","A jacket","A shoe with laces","Something striped","Something with a zip","A piece of jewellery","Something you wear when it rains"]),
  ...scavenger("Letters & Numbers","The requested character must be clearly printed on a physical object.",["Something with the letter S","Something with the letter A","Something with the letter Z","Something with the number 5","Something with a two-digit number","Something with a barcode","Something with your initials"]),
  ...scavenger("Creative","Accept any safe object that reasonably satisfies the description.",["Something smaller than your hand","Something that makes a noise","Something soft","Something round","Something made of wood","Something transparent","Something older than five years","Two objects of the same colour","Something normally kept in a kitchen","Something that smells pleasant","Something that can roll","Something beginning with B","A South African product","Something with a handle","Something you can recycle"]),
];

// Produce Bomb uses real photographs resolved from Wikipedia / Wikimedia Commons at runtime.
// The internal bomb mode id remains "veggies" for backwards compatibility with saved rooms.
const produce=(prompt:string,wikipediaTitle?:string,aliases:string[]=[])=>({gameType:"bomb" as const,prompt,answer:prompt,category:"Produce",metadata:{bombMode:"veggies",wikipediaTitle:wikipediaTitle??prompt,aliases,attribution:"Wikipedia / Wikimedia Commons"}});
const PRODUCE:PhysicalCard[]=[
  produce("Apple",undefined,[]),
  produce("Apricot",undefined,[]),
  produce("Avocado",undefined,[]),
  produce("Banana",undefined,[]),
  produce("Plantain","Cooking banana",["cooking banana"]),
  produce("Orange","Orange (fruit)",[]),
  produce("Mandarin","Mandarin orange",[]),
  produce("Clementine",undefined,[]),
  produce("Tangerine",undefined,[]),
  produce("Satsuma",undefined,[]),
  produce("Lemon",undefined,[]),
  produce("Lime","Lime (fruit)",[]),
  produce("Grapefruit",undefined,[]),
  produce("Pomelo",undefined,[]),
  produce("Kumquat",undefined,[]),
  produce("Yuzu",undefined,[]),
  produce("Bergamot orange",undefined,[]),
  produce("Blood orange",undefined,[]),
  produce("Ugli fruit","Jamaican tangelo",[]),
  produce("Sweet lime","Citrus limetta",[]),
  produce("Citron",undefined,[]),
  produce("Finger lime",undefined,[]),
  produce("Key lime",undefined,[]),
  produce("Persian lime",undefined,[]),
  produce("Calamansi",undefined,[]),
  produce("Strawberry",undefined,[]),
  produce("Blueberry",undefined,[]),
  produce("Raspberry",undefined,[]),
  produce("Blackberry",undefined,[]),
  produce("Cranberry",undefined,[]),
  produce("Gooseberry",undefined,[]),
  produce("Blackcurrant",undefined,[]),
  produce("Redcurrant",undefined,[]),
  produce("White currant",undefined,[]),
  produce("Boysenberry",undefined,[]),
  produce("Loganberry",undefined,[]),
  produce("Cloudberry",undefined,[]),
  produce("Lingonberry","Vaccinium vitis-idaea",[]),
  produce("Mulberry",undefined,[]),
  produce("Elderberry","Sambucus",[]),
  produce("Huckleberry",undefined,[]),
  produce("Salmonberry","Rubus spectabilis",[]),
  produce("Tayberry",undefined,[]),
  produce("Marionberry",undefined,[]),
  produce("Acai berry","Açaí palm",[]),
  produce("Aronia berry","Aronia",[]),
  produce("Sea buckthorn","Hippophae",[]),
  produce("Cape gooseberry","Physalis peruviana",["physalis","goldenberry"]),
  produce("Goji berry","Goji",[]),
  produce("Bilberry",undefined,[]),
  produce("Cherry",undefined,[]),
  produce("Sour cherry","Prunus cerasus",[]),
  produce("Sweet cherry","Prunus avium",[]),
  produce("Peach",undefined,[]),
  produce("Nectarine",undefined,[]),
  produce("Plum",undefined,[]),
  produce("Damson",undefined,[]),
  produce("Greengage",undefined,[]),
  produce("Mirabelle plum",undefined,[]),
  produce("Aprium",undefined,[]),
  produce("Pluot",undefined,[]),
  produce("Mango",undefined,[]),
  produce("Papaya",undefined,[]),
  produce("Pineapple",undefined,[]),
  produce("Guava",undefined,[]),
  produce("Feijoa","Feijoa sellowiana",[]),
  produce("Passion fruit","Passiflora edulis",[]),
  produce("Dragon fruit","Pitaya",["pitaya"]),
  produce("Lychee",undefined,[]),
  produce("Longan",undefined,[]),
  produce("Rambutan",undefined,[]),
  produce("Mangosteen",undefined,[]),
  produce("Durian",undefined,[]),
  produce("Jackfruit",undefined,[]),
  produce("Breadfruit",undefined,[]),
  produce("Starfruit","Carambola",[]),
  produce("Soursop",undefined,[]),
  produce("Cherimoya",undefined,[]),
  produce("Custard apple","Annona reticulata",[]),
  produce("Sugar apple","Sugar-apple",[]),
  produce("Sapodilla","Manilkara zapota",[]),
  produce("Tamarind",undefined,[]),
  produce("Persimmon",undefined,[]),
  produce("Pomegranate",undefined,[]),
  produce("Fig","Common fig",[]),
  produce("Date","Date palm",[]),
  produce("Coconut",undefined,[]),
  produce("Kiwifruit",undefined,["kiwi"]),
  produce("Watermelon",undefined,[]),
  produce("Cantaloupe",undefined,["rockmelon"]),
  produce("Honeydew melon","Honeydew (melon)",[]),
  produce("Galia melon",undefined,[]),
  produce("Canary melon",undefined,[]),
  produce("Hami melon",undefined,[]),
  produce("Kiwano","Cucumis metuliferus",[]),
  produce("Casaba melon",undefined,[]),
  produce("Crenshaw melon",undefined,[]),
  produce("Asian pear","Pyrus pyrifolia",[]),
  produce("Pear",undefined,[]),
  produce("Quince",undefined,[]),
  produce("Loquat",undefined,[]),
  produce("Medlar","Mespilus germanica",[]),
  produce("Jujube",undefined,[]),
  produce("Nashi pear","Pyrus pyrifolia",[]),
  produce("Pawpaw","Asimina triloba",[]),
  produce("Ackee",undefined,[]),
  produce("Breadnut","Brosimum alicastrum",[]),
  produce("Rose apple","Syzygium jambos",[]),
  produce("Wax apple","Syzygium samarangense",[]),
  produce("Java plum","Syzygium cumini",[]),
  produce("Santol","Sandoricum koetjape",[]),
  produce("Langsat","Lansium parasiticum",[]),
  produce("Salak",undefined,[]),
  produce("Miracle fruit","Synsepalum dulcificum",[]),
  produce("Star apple","Chrysophyllum cainito",[]),
  produce("Mamey sapote","Pouteria sapota",[]),
  produce("Black sapote","Diospyros nigra",[]),
  produce("White sapote","Casimiroa edulis",[]),
  produce("Canistel","Pouteria campechiana",[]),
  produce("Lucuma","Pouteria lucuma",[]),
  produce("Jabuticaba",undefined,[]),
  produce("Cupuacu","Theobroma grandiflorum",[]),
  produce("Atemoya",undefined,[]),
  produce("Bael","Aegle marmelos",[]),
  produce("Wood apple","Limonia acidissima",[]),
  produce("Buddha's hand",undefined,[]),
  produce("Noni","Morinda citrifolia",[]),
  produce("Prickly pear","Opuntia",[]),
  produce("Barbados cherry","Malpighia emarginata",[]),
  produce("Surinam cherry","Eugenia uniflora",[]),
  produce("Monstera fruit","Monstera deliciosa",[]),
  produce("Pepino melon","Solanum muricatum",[]),
  produce("Tamarillo",undefined,[]),
  produce("Physalis",undefined,["cape gooseberry","goldenberry"]),
  produce("Olive",undefined,[]),
  produce("Grape",undefined,[]),
  produce("Concord grape",undefined,[]),
  produce("Muscat grape","Muscat (grape)",[]),
  produce("Red banana",undefined,[]),
  produce("Lady Finger banana",undefined,[]),
  produce("Horned melon","Cucumis metuliferus",[]),
  produce("Young coconut","Coconut",[]),
  produce("Cacao pod","Theobroma cacao",[]),
  produce("Camu camu","Myrciaria dubia",[]),
  produce("Mamoncillo","Melicoccus bijugatus",[]),
  produce("Pulasan",undefined,[]),
  produce("Ambarella","Spondias dulcis",[]),
  produce("June plum","Spondias dulcis",[]),
  produce("Hog plum","Spondias mombin",[]),
  produce("Indian gooseberry","Phyllanthus emblica",[]),
  produce("Kakadu plum","Terminalia ferdinandiana",[]),
  produce("Bignay","Antidesma bunius",[]),
  produce("Marula","Sclerocarya birrea",[]),
  produce("Kei apple","Dovyalis caffra",[]),
  produce("Natal plum","Carissa macrocarpa",[]),
  produce("Monkey orange","Strychnos spinosa",[]),
  produce("African horned cucumber","Cucumis metuliferus",[]),
  produce("Desert lime","Citrus glauca",[]),
  produce("Davidson's plum","Davidsonia",[]),
  produce("Quandong","Santalum acuminatum",[]),
  produce("Riberry","Syzygium luehmannii",[]),
  produce("Illawarra plum","Podocarpus elatus",[]),
  produce("Mountain pepper berry","Tasmannia lanceolata",[]),
  produce("Carrot",undefined,[]),
  produce("Purple carrot","Carrot",[]),
  produce("Parsnip",undefined,[]),
  produce("Turnip",undefined,[]),
  produce("Swede","Rutabaga",["rutabaga"]),
  produce("Radish",undefined,[]),
  produce("Daikon",undefined,[]),
  produce("Beetroot",undefined,["beet"]),
  produce("Golden beet","Beetroot",[]),
  produce("Celeriac",undefined,[]),
  produce("Jerusalem artichoke",undefined,[]),
  produce("Sweet potato",undefined,[]),
  produce("Potato",undefined,[]),
  produce("Yam","Yam (vegetable)",[]),
  produce("Cassava",undefined,[]),
  produce("Taro",undefined,[]),
  produce("Eddoe",undefined,[]),
  produce("Jicama","Pachyrhizus erosus",[]),
  produce("Yacon","Yacón",[]),
  produce("Lotus root","Nelumbo nucifera",[]),
  produce("Ginger",undefined,[]),
  produce("Turmeric",undefined,[]),
  produce("Horseradish",undefined,[]),
  produce("Wasabi",undefined,[]),
  produce("Onion",undefined,[]),
  produce("Red onion",undefined,[]),
  produce("White onion","Onion",[]),
  produce("Yellow onion","Onion",[]),
  produce("Shallot",undefined,[]),
  produce("Spring onion","Scallion",["scallion","green onion"]),
  produce("Leek",undefined,[]),
  produce("Garlic",undefined,[]),
  produce("Elephant garlic",undefined,[]),
  produce("Chives",undefined,[]),
  produce("Broccoli",undefined,[]),
  produce("Broccolini",undefined,[]),
  produce("Cauliflower",undefined,[]),
  produce("Romanesco broccoli",undefined,[]),
  produce("Cabbage",undefined,[]),
  produce("Red cabbage",undefined,[]),
  produce("Savoy cabbage",undefined,[]),
  produce("Napa cabbage",undefined,["Chinese cabbage"]),
  produce("Bok choy",undefined,["pak choi"]),
  produce("Brussels sprouts","Brussels sprout",[]),
  produce("Kale",undefined,[]),
  produce("Collard greens","Collard (plant)",[]),
  produce("Spinach",undefined,[]),
  produce("Swiss chard","Chard",[]),
  produce("Lettuce",undefined,[]),
  produce("Romaine lettuce",undefined,[]),
  produce("Iceberg lettuce",undefined,[]),
  produce("Butterhead lettuce","Lettuce",[]),
  produce("Rocket","Arugula",["arugula"]),
  produce("Watercress",undefined,[]),
  produce("Endive",undefined,[]),
  produce("Chicory","Common chicory",[]),
  produce("Radicchio",undefined,[]),
  produce("Mustard greens","Brassica juncea",[]),
  produce("Turnip greens","Turnip",[]),
  produce("Beet greens","Beetroot",[]),
  produce("Sorrel",undefined,[]),
  produce("Dandelion greens","Taraxacum officinale",[]),
  produce("Mizuna",undefined,[]),
  produce("Tatsoi",undefined,[]),
  produce("Komatsuna",undefined,[]),
  produce("Amaranth greens","Amaranth",[]),
  produce("Malabar spinach","Basella alba",[]),
  produce("New Zealand spinach","Tetragonia tetragonioides",[]),
  produce("Okra",undefined,[]),
  produce("Aubergine","Eggplant",["eggplant"]),
  produce("White aubergine","Eggplant",[]),
  produce("Thai aubergine","Thai eggplant",[]),
  produce("Tomato",undefined,[]),
  produce("Cherry tomato",undefined,[]),
  produce("Plum tomato",undefined,[]),
  produce("Beefsteak tomato",undefined,[]),
  produce("Green tomato","Tomato",[]),
  produce("Tomatillo",undefined,[]),
  produce("Bell pepper",undefined,["sweet pepper","capsicum"]),
  produce("Red bell pepper","Bell pepper",[]),
  produce("Yellow bell pepper","Bell pepper",[]),
  produce("Green bell pepper","Bell pepper",[]),
  produce("Orange bell pepper","Bell pepper",[]),
  produce("Chilli pepper","Chili pepper",["chili pepper","hot pepper"]),
  produce("Jalapeño",undefined,[]),
  produce("Serrano pepper",undefined,[]),
  produce("Poblano",undefined,[]),
  produce("Habanero",undefined,[]),
  produce("Scotch bonnet",undefined,[]),
  produce("Cayenne pepper",undefined,[]),
  produce("Bird's eye chilli","Bird's eye chili",[]),
  produce("Anaheim pepper","New Mexico chile",[]),
  produce("Banana pepper",undefined,[]),
  produce("Shishito pepper","Shishito",[]),
  produce("Padron pepper","Padrón pepper",[]),
  produce("Ghost pepper","Bhut jolokia",[]),
  produce("Carolina Reaper",undefined,[]),
  produce("Cucumber",undefined,[]),
  produce("English cucumber","Cucumber",[]),
  produce("Gherkin",undefined,[]),
  produce("Armenian cucumber",undefined,[]),
  produce("Courgette","Zucchini",["zucchini"]),
  produce("Yellow squash","Summer squash",[]),
  produce("Pattypan squash",undefined,[]),
  produce("Butternut squash",undefined,[]),
  produce("Acorn squash",undefined,[]),
  produce("Spaghetti squash",undefined,[]),
  produce("Kabocha",undefined,[]),
  produce("Delicata squash",undefined,[]),
  produce("Hubbard squash",undefined,[]),
  produce("Pumpkin",undefined,[]),
  produce("Gem squash","Cucurbita pepo",[]),
  produce("Chayote",undefined,[]),
  produce("Bitter melon","Momordica charantia",[]),
  produce("Bottle gourd","Calabash",[]),
  produce("Ridge gourd","Luffa acutangula",[]),
  produce("Snake gourd","Trichosanthes cucumerina",[]),
  produce("Ash gourd","Benincasa hispida",[]),
  produce("Luffa",undefined,[]),
  produce("Sweetcorn","Sweet corn",["corn","maize"]),
  produce("Baby corn",undefined,[]),
  produce("Green peas","Pea",["peas"]),
  produce("Snow peas","Snow pea",[]),
  produce("Sugar snap peas","Snap pea",[]),
  produce("Green beans","Green bean",[]),
  produce("Runner beans","Runner bean",[]),
  produce("Broad beans","Vicia faba",["fava beans"]),
  produce("Lima beans","Lima bean",[]),
  produce("Edamame",undefined,[]),
  produce("Soybeans","Soybean",[]),
  produce("Black beans","Black bean",[]),
  produce("Kidney beans","Kidney bean",[]),
  produce("Pinto beans","Pinto bean",[]),
  produce("Cannellini beans","Kidney bean",[]),
  produce("Chickpeas","Chickpea",[]),
  produce("Lentils","Lentil",[]),
  produce("Mung beans","Mung bean",[]),
  produce("Adzuki beans","Adzuki bean",[]),
  produce("Black-eyed peas","Black-eyed pea",[]),
  produce("Bambara groundnut",undefined,[]),
  produce("Winged bean",undefined,[]),
  produce("Yardlong bean",undefined,[]),
  produce("Artichoke",undefined,[]),
  produce("Asparagus",undefined,[]),
  produce("Celery",undefined,[]),
  produce("Fennel",undefined,[]),
  produce("Kohlrabi",undefined,[]),
  produce("Bamboo shoots","Bamboo shoot",[]),
  produce("Hearts of palm","Heart of palm",[]),
  produce("Fiddlehead fern",undefined,[]),
  produce("Samphire","Salicornia",[]),
  produce("Sea kale","Crambe maritima",[]),
  produce("Cardoon",undefined,[]),
  produce("Rhubarb",undefined,[]),
  produce("Nopales","Nopal",[]),
  produce("Mushroom","Edible mushroom",[]),
  produce("Button mushroom","Agaricus bisporus",[]),
  produce("Portobello mushroom","Agaricus bisporus",[]),
  produce("Shiitake",undefined,[]),
  produce("Oyster mushroom","Pleurotus ostreatus",[]),
  produce("Enoki","Enokitake",[]),
  produce("King oyster mushroom","Pleurotus eryngii",[]),
  produce("Maitake","Grifola frondosa",[]),
  produce("Morel","Morchella",[]),
  produce("Chanterelle",undefined,[]),
  produce("Porcini","Boletus edulis",[]),
  produce("Wood ear mushroom","Auricularia auricula-judae",[]),
  produce("Lion's mane mushroom","Hericium erinaceus",[]),
  produce("Bean sprouts","Bean sprout",[]),
  produce("Alfalfa sprouts","Alfalfa",[]),
  produce("Broccoli sprouts",undefined,[]),
  produce("Microgreens","Microgreen",[]),
  produce("Parsley",undefined,[]),
  produce("Coriander",undefined,["cilantro"]),
  produce("Basil",undefined,[]),
  produce("Mint","Mentha",[]),
  produce("Dill",undefined,[]),
  produce("Rosemary",undefined,[]),
  produce("Thyme",undefined,[]),
  produce("Sage","Salvia officinalis",[]),
  produce("Oregano",undefined,[]),
  produce("Marjoram",undefined,[]),
  produce("Tarragon",undefined,[]),
  produce("Lemongrass","Cymbopogon",[]),
  produce("Bay leaf",undefined,[]),
  produce("Lovage",undefined,[]),
  produce("Chervil",undefined,[]),
  produce("Curry leaves","Curry tree",[]),
  produce("Fenugreek leaves","Fenugreek",[]),
  produce("Perilla","Perilla frutescens",[]),
  produce("Shiso","Perilla frutescens",[]),
  produce("Purslane","Portulaca oleracea",[]),
  produce("Moringa leaves","Moringa oleifera",[]),
  produce("Cassava leaves","Cassava",[]),
  produce("Pumpkin leaves","Pumpkin",[]),
  produce("Grape leaves","Grape leaf",[]),
  produce("Banana blossom","Banana",[]),
  produce("Palm cabbage","Heart of palm",[]),
  produce("Water spinach","Ipomoea aquatica",["kangkong"]),
  produce("Chinese broccoli","Gai lan",["gai lan"]),
  produce("Chinese celery","Leaf celery",[]),
  produce("Celtuce",undefined,[]),
  produce("Pea shoots","Pea",[]),
  produce("Garlic scapes","Garlic scape",[]),
  produce("Onion sprouts","Onion",[]),
];

const punctuation=(symbol:string,answer:string,example:string,aliases:string[]=[],difficulty="Easy")=>({gameType:"bomb" as const,prompt:symbol,answer,category:"Punctuation",metadata:{bombMode:"punctuation",aliases,difficulty,example}});
const PUNCTUATION:PhysicalCard[]=[
  punctuation(".","full stop","The game is over.",["period"]),
  punctuation(",","comma","Ready, set, go!"),
  punctuation("?","question mark","Are you ready?"),
  punctuation("!","exclamation mark","Hi!",["exclamation point"]),
  punctuation(":","colon","Bring three things: water, shoes and a hat."),
  punctuation(";","semicolon","It was late; we kept playing.",["semi-colon"]),
  punctuation("'","apostrophe","Lerato's turn",["single quote"]),
  punctuation('"',"quotation marks",'She said, "Go!"',["double quotes","inverted commas"]),
  punctuation("()","round brackets","The answer (ten) is correct.",["parentheses"]),
  punctuation("[]","square brackets","Add the missing word: She [runs] daily.",["brackets"]),
  punctuation("{}","curly brackets","Set = {1, 2, 3}",["braces"]),
  punctuation("/","forward slash","and/or",["slash"]),
  punctuation("\\","backslash","C:\\Games\\Bomb"),
  punctuation("-","hyphen","twenty-one"),
  punctuation("_","underscore","team_name"),
  punctuation("…","ellipsis","Wait for it…",["three dots"]),
  punctuation("@","at sign","player@example.com",["at symbol"]),
  punctuation("#","hash","#GameNight",["number sign","pound sign"]),
  punctuation("&","ampersand","music & games",["and sign"]),
  punctuation("*","asterisk","Winner*",["star"]),
  punctuation("–","en dash","Pages 10–15",[],"Hard"),
  punctuation("—","em dash","The winner—Team A—celebrated.",[],"Hard"),
  punctuation("<>","angle brackets","3 < 5 > 2",["chevrons"],"Hard"),
  punctuation("|","vertical bar","|-5| = 5",["pipe","absolute value bars"],"Hard"),
];

export const PHYSICAL_GAMES_CONTENT:readonly PhysicalCard[]=[...CHARADES,...SCAVENGER,...PRODUCE,...PUNCTUATION];
