export type TabooCard = readonly [
  prompt: string,
  category: string,
  prohibited: readonly [string, string, string, string, string],
];

// Original Game Night ZA cards. Each list blocks the five most natural ways
// a clue-giver would explain the target; related-but-unhelpful words are avoided.
export const TABOO_BANK: readonly TabooCard[] = [
  ["Square", "Objects & Shapes", ["four", "equal", "sides", "corners", "box"]],
  ["Circle", "Objects & Shapes", ["round", "shape", "ring", "ball", "centre"]],
  ["Triangle", "Objects & Shapes", ["three", "sides", "corners", "shape", "angle"]],
  ["Rectangle", "Objects & Shapes", ["four", "sides", "long", "shape", "opposite"]],
  ["Pencil", "Everyday Objects", ["write", "draw", "eraser", "sharpener", "lead"]],
  ["Eraser", "Everyday Objects", ["rubber", "pencil", "mistake", "remove", "school"]],
  ["Scissors", "Everyday Objects", ["cut", "blades", "paper", "sharp", "pair"]],
  ["Umbrella", "Everyday Objects", ["rain", "wet", "cover", "handle", "open"]],
  ["Mirror", "Everyday Objects", ["reflection", "glass", "look", "face", "image"]],
  ["Pillow", "Everyday Objects", ["sleep", "head", "bed", "soft", "cushion"]],
  ["Blanket", "Everyday Objects", ["warm", "bed", "cover", "sleep", "cold"]],
  ["Toothbrush", "Everyday Objects", ["teeth", "paste", "clean", "bathroom", "bristles"]],
  ["Candle", "Everyday Objects", ["wax", "flame", "light", "burn", "wick"]],
  ["Clock", "Everyday Objects", ["time", "hours", "hands", "wall", "tick"]],
  ["Key", "Everyday Objects", ["lock", "door", "open", "metal", "unlock"]],
  ["Wallet", "Everyday Objects", ["money", "cards", "pocket", "cash", "leather"]],
  ["Backpack", "Everyday Objects", ["bag", "school", "shoulders", "carry", "zip"]],
  ["Ladder", "Everyday Objects", ["climb", "steps", "height", "roof", "rungs"]],
  ["Hammer", "Everyday Objects", ["nail", "hit", "tool", "wood", "build"]],
  ["Screwdriver", "Everyday Objects", ["screw", "tool", "turn", "handle", "tighten"]],
  ["Broom", "Everyday Objects", ["sweep", "floor", "clean", "dust", "bristles"]],
  ["Bucket", "Everyday Objects", ["water", "handle", "carry", "container", "plastic"]],
  ["Fridge", "Everyday Objects", ["cold", "food", "kitchen", "freezer", "door"]],
  ["Microwave", "Everyday Objects", ["heat", "food", "kitchen", "seconds", "oven"]],
  ["Kettle", "Everyday Objects", ["boil", "water", "tea", "hot", "kitchen"]],
  ["Washing Machine", "Everyday Objects", ["clothes", "laundry", "wash", "spin", "detergent"]],
  ["Remote Control", "Everyday Objects", ["television", "buttons", "channel", "volume", "battery"]],
  ["Sunglasses", "Everyday Objects", ["sun", "eyes", "dark", "wear", "shades"]],
  ["Headphones", "Everyday Objects", ["music", "ears", "listen", "sound", "wireless"]],
  ["Camera", "Everyday Objects", ["photo", "picture", "lens", "take", "flash"]],

  ["Pizza", "Food & Drink", ["cheese", "slice", "toppings", "dough", "Italian"]],
  ["Burger", "Food & Drink", ["bun", "patty", "beef", "cheese", "fast food"]],
  ["Sandwich", "Food & Drink", ["bread", "filling", "lunch", "slices", "toast"]],
  ["Chocolate", "Food & Drink", ["sweet", "cocoa", "bar", "brown", "dessert"]],
  ["Ice Cream", "Food & Drink", ["cold", "scoop", "cone", "melt", "flavour"]],
  ["Popcorn", "Food & Drink", ["cinema", "movie", "corn", "snack", "butter"]],
  ["Coffee", "Food & Drink", ["drink", "caffeine", "beans", "cup", "morning"]],
  ["Tea", "Food & Drink", ["drink", "cup", "bag", "hot", "milk"]],
  ["Milk", "Food & Drink", ["cow", "white", "drink", "cereal", "dairy"]],
  ["Bread", "Food & Drink", ["loaf", "slice", "toast", "sandwich", "bake"]],
  ["Cheese", "Food & Drink", ["dairy", "milk", "yellow", "slice", "melt"]],
  ["Egg", "Food & Drink", ["chicken", "shell", "yolk", "breakfast", "boil"]],
  ["Banana", "Food & Drink", ["yellow", "fruit", "peel", "monkey", "bunch"]],
  ["Apple", "Food & Drink", ["fruit", "red", "green", "tree", "bite"]],
  ["Watermelon", "Food & Drink", ["fruit", "green", "red", "seeds", "summer"]],
  ["Lemon", "Food & Drink", ["yellow", "sour", "fruit", "juice", "citrus"]],
  ["Potato", "Food & Drink", ["chips", "vegetable", "mash", "peel", "starch"]],
  ["Rice", "Food & Drink", ["grain", "white", "cook", "bowl", "staple"]],
  ["Pasta", "Food & Drink", ["Italian", "noodles", "sauce", "spaghetti", "boil"]],
  ["Soup", "Food & Drink", ["bowl", "liquid", "hot", "spoon", "broth"]],
  ["Salad", "Food & Drink", ["lettuce", "healthy", "vegetables", "bowl", "dressing"]],
  ["Cake", "Food & Drink", ["birthday", "icing", "bake", "slice", "candles"]],
  ["Doughnut", "Food & Drink", ["round", "hole", "sweet", "fried", "icing"]],
  ["Biscuit", "Food & Drink", ["cookie", "crunchy", "tea", "snack", "bake"]],
  ["Honey", "Food & Drink", ["bee", "sweet", "sticky", "hive", "golden"]],
  ["Salt", "Food & Drink", ["seasoning", "white", "pepper", "taste", "shaker"]],
  ["Sugar", "Food & Drink", ["sweet", "white", "tea", "spoon", "baking"]],
  ["Braai", "South African Food", ["meat", "fire", "barbecue", "grill", "charcoal"]],
  ["Boerewors", "South African Food", ["sausage", "braai", "meat", "coil", "farmer"]],
  ["Bunny Chow", "South African Food", ["Durban", "curry", "bread", "loaf", "Indian"]],

  ["Teacher", "People & Jobs", ["school", "students", "classroom", "lesson", "teach"]],
  ["Doctor", "People & Jobs", ["hospital", "patient", "sick", "medicine", "health"]],
  ["Nurse", "People & Jobs", ["hospital", "patient", "doctor", "care", "uniform"]],
  ["Police Officer", "People & Jobs", ["crime", "arrest", "law", "uniform", "station"]],
  ["Firefighter", "People & Jobs", ["fire", "hose", "rescue", "truck", "flames"]],
  ["Chef", "People & Jobs", ["cook", "kitchen", "food", "restaurant", "hat"]],
  ["Pilot", "People & Jobs", ["plane", "fly", "cockpit", "airport", "captain"]],
  ["Farmer", "People & Jobs", ["crops", "animals", "tractor", "land", "farm"]],
  ["Mechanic", "People & Jobs", ["car", "repair", "engine", "garage", "tools"]],
  ["Dentist", "People & Jobs", ["teeth", "mouth", "drill", "cavity", "braces"]],
  ["Lawyer", "People & Jobs", ["court", "judge", "law", "client", "case"]],
  ["Barber", "People & Jobs", ["hair", "cut", "clippers", "salon", "shave"]],
  ["Cashier", "People & Jobs", ["till", "shop", "money", "pay", "receipt"]],
  ["Waiter", "People & Jobs", ["restaurant", "table", "order", "food", "serve"]],
  ["DJ", "People & Jobs", ["music", "club", "mix", "party", "turntable"]],
  ["Photographer", "People & Jobs", ["camera", "pictures", "photos", "lens", "shoot"]],
  ["Plumber", "People & Jobs", ["pipes", "water", "leak", "toilet", "repair"]],
  ["Electrician", "People & Jobs", ["wires", "power", "electricity", "lights", "repair"]],
  ["Coach", "People & Jobs", ["team", "sport", "train", "players", "manager"]],
  ["Referee", "People & Jobs", ["whistle", "match", "rules", "official", "foul"]],
  ["Baby", "People & Jobs", ["cry", "nappy", "small", "mother", "newborn"]],
  ["Grandmother", "People & Jobs", ["granny", "family", "old", "mother", "grandchildren"]],
  ["Twin", "People & Jobs", ["two", "same", "born", "identical", "siblings"]],
  ["Celebrity", "People & Jobs", ["famous", "star", "fans", "public", "Hollywood"]],
  ["President", "People & Jobs", ["country", "leader", "government", "election", "office"]],

  ["School", "Places & Travel", ["students", "teacher", "classroom", "learn", "education"]],
  ["Hospital", "Places & Travel", ["doctor", "nurse", "patient", "sick", "emergency"]],
  ["Airport", "Places & Travel", ["plane", "flight", "passport", "luggage", "terminal"]],
  ["Beach", "Places & Travel", ["sand", "ocean", "waves", "swim", "sun"]],
  ["Restaurant", "Places & Travel", ["food", "menu", "waiter", "eat", "table"]],
  ["Hotel", "Places & Travel", ["room", "sleep", "guest", "reception", "holiday"]],
  ["Library", "Places & Travel", ["books", "read", "quiet", "borrow", "shelves"]],
  ["Supermarket", "Places & Travel", ["groceries", "shopping", "trolley", "aisles", "food"]],
  ["Cinema", "Places & Travel", ["movie", "screen", "popcorn", "film", "seats"]],
  ["Stadium", "Places & Travel", ["sport", "crowd", "match", "seats", "field"]],
  ["Church", "Places & Travel", ["pray", "God", "worship", "pastor", "Sunday"]],
  ["Bank", "Places & Travel", ["money", "account", "cash", "loan", "deposit"]],
  ["Prison", "Places & Travel", ["jail", "cell", "criminal", "bars", "sentence"]],
  ["Museum", "Places & Travel", ["history", "art", "exhibits", "old", "gallery"]],
  ["Zoo", "Places & Travel", ["animals", "cages", "visit", "wild", "park"]],
  ["Farm", "Places & Travel", ["animals", "crops", "tractor", "farmer", "land"]],
  ["Mountain", "Places & Travel", ["high", "climb", "peak", "hill", "rock"]],
  ["Desert", "Places & Travel", ["sand", "dry", "hot", "camel", "water"]],
  ["Island", "Places & Travel", ["water", "ocean", "land", "beach", "surrounded"]],
  ["Forest", "Places & Travel", ["trees", "woods", "animals", "green", "nature"]],
  ["Waterfall", "Places & Travel", ["water", "fall", "river", "cliff", "flow"]],
  ["Bus Stop", "Places & Travel", ["bus", "wait", "transport", "route", "shelter"]],
  ["Taxi Rank", "Places & Travel", ["minibus", "transport", "driver", "queue", "fare"]],
  ["Petrol Station", "Places & Travel", ["fuel", "car", "diesel", "pump", "garage"]],
  ["Shopping Mall", "Places & Travel", ["shops", "stores", "buy", "food court", "centre"]],

  ["Elephant", "Animals & Nature", ["trunk", "tusks", "grey", "large", "animal"]],
  ["Lion", "Animals & Nature", ["king", "roar", "mane", "cat", "Africa"]],
  ["Giraffe", "Animals & Nature", ["neck", "tall", "spots", "animal", "Africa"]],
  ["Zebra", "Animals & Nature", ["stripes", "black", "white", "horse", "animal"]],
  ["Dog", "Animals & Nature", ["bark", "pet", "puppy", "tail", "bone"]],
  ["Cat", "Animals & Nature", ["meow", "pet", "kitten", "whiskers", "purr"]],
  ["Horse", "Animals & Nature", ["ride", "saddle", "gallop", "stable", "pony"]],
  ["Cow", "Animals & Nature", ["milk", "moo", "farm", "beef", "horns"]],
  ["Chicken", "Animals & Nature", ["egg", "bird", "farm", "cluck", "wings"]],
  ["Penguin", "Animals & Nature", ["ice", "bird", "black", "white", "Antarctica"]],
  ["Dolphin", "Animals & Nature", ["ocean", "swim", "intelligent", "mammal", "flipper"]],
  ["Shark", "Animals & Nature", ["ocean", "teeth", "fin", "dangerous", "fish"]],
  ["Snake", "Animals & Nature", ["slither", "venom", "long", "reptile", "bite"]],
  ["Spider", "Animals & Nature", ["eight", "legs", "web", "insect", "bite"]],
  ["Butterfly", "Animals & Nature", ["wings", "colourful", "caterpillar", "fly", "insect"]],
  ["Bee", "Animals & Nature", ["honey", "sting", "hive", "buzz", "yellow"]],
  ["Mosquito", "Animals & Nature", ["bite", "blood", "buzz", "itch", "insect"]],
  ["Crocodile", "Animals & Nature", ["teeth", "river", "reptile", "dangerous", "alligator"]],
  ["Monkey", "Animals & Nature", ["banana", "tree", "ape", "swing", "animal"]],
  ["Kangaroo", "Animals & Nature", ["Australia", "jump", "pouch", "joey", "animal"]],
  ["Volcano", "Animals & Nature", ["lava", "erupt", "mountain", "ash", "hot"]],
  ["Rainbow", "Animals & Nature", ["colours", "sky", "rain", "arc", "seven"]],
  ["Thunder", "Animals & Nature", ["storm", "sound", "lightning", "loud", "sky"]],
  ["Lightning", "Animals & Nature", ["flash", "storm", "thunder", "sky", "electric"]],
  ["Snow", "Animals & Nature", ["white", "cold", "winter", "ice", "flakes"]],
  ["Rain", "Animals & Nature", ["water", "clouds", "wet", "umbrella", "weather"]],
  ["Sun", "Animals & Nature", ["hot", "sky", "light", "day", "star"]],
  ["Moon", "Animals & Nature", ["night", "sky", "space", "full", "orbit"]],
  ["Star", "Animals & Nature", ["sky", "night", "space", "shine", "sun"]],
  ["Ocean", "Animals & Nature", ["water", "sea", "waves", "deep", "salt"]],

  ["Football", "Sport & Entertainment", ["goal", "kick", "ball", "pitch", "soccer"]],
  ["Rugby", "Sport & Entertainment", ["ball", "tackle", "try", "scrum", "Springboks"]],
  ["Cricket", "Sport & Entertainment", ["bat", "ball", "wicket", "bowler", "runs"]],
  ["Basketball", "Sport & Entertainment", ["ball", "hoop", "dribble", "court", "shoot"]],
  ["Tennis", "Sport & Entertainment", ["racket", "ball", "court", "serve", "net"]],
  ["Golf", "Sport & Entertainment", ["club", "ball", "hole", "course", "swing"]],
  ["Boxing", "Sport & Entertainment", ["gloves", "fight", "ring", "punch", "round"]],
  ["Swimming", "Sport & Entertainment", ["water", "pool", "stroke", "race", "dive"]],
  ["Marathon", "Sport & Entertainment", ["run", "race", "distance", "kilometres", "finish"]],
  ["Gym", "Sport & Entertainment", ["exercise", "weights", "fitness", "workout", "train"]],
  ["Trophy", "Sport & Entertainment", ["win", "prize", "cup", "champion", "award"]],
  ["Whistle", "Sport & Entertainment", ["blow", "sound", "referee", "mouth", "loud"]],
  ["Guitar", "Sport & Entertainment", ["strings", "instrument", "play", "chords", "electric"]],
  ["Piano", "Sport & Entertainment", ["keys", "instrument", "play", "music", "black"]],
  ["Drum", "Sport & Entertainment", ["beat", "sticks", "instrument", "rhythm", "hit"]],
  ["Microphone", "Sport & Entertainment", ["sing", "voice", "sound", "stage", "speak"]],
  ["Movie", "Sport & Entertainment", ["film", "cinema", "watch", "actor", "screen"]],
  ["Television", "Sport & Entertainment", ["screen", "watch", "channel", "remote", "show"]],
  ["Netflix", "Sport & Entertainment", ["stream", "watch", "series", "movies", "subscription"]],
  ["TikTok", "Sport & Entertainment", ["video", "app", "live", "scroll", "social media"]],
  ["Selfie", "Sport & Entertainment", ["photo", "phone", "yourself", "camera", "picture"]],
  ["Video Game", "Sport & Entertainment", ["play", "console", "controller", "computer", "gaming"]],
  ["Puzzle", "Sport & Entertainment", ["pieces", "solve", "picture", "jigsaw", "fit"]],
  ["Magic", "Sport & Entertainment", ["trick", "illusion", "magician", "wand", "disappear"]],
  ["Dance", "Sport & Entertainment", ["music", "move", "rhythm", "steps", "body"]],
  ["Karaoke", "Sport & Entertainment", ["sing", "lyrics", "microphone", "music", "screen"]],
  ["Wedding", "Sport & Entertainment", ["bride", "groom", "marriage", "ring", "ceremony"]],
  ["Birthday", "Sport & Entertainment", ["cake", "candles", "party", "age", "celebrate"]],
  ["Christmas", "Sport & Entertainment", ["December", "Santa", "gifts", "tree", "holiday"]],
  ["Concert", "Sport & Entertainment", ["music", "stage", "crowd", "singer", "live"]],

  ["Smartphone", "Technology", ["mobile", "call", "apps", "screen", "device"]],
  ["Laptop", "Technology", ["computer", "keyboard", "screen", "portable", "battery"]],
  ["Internet", "Technology", ["online", "website", "connect", "web", "Wi-Fi"]],
  ["Wi-Fi", "Technology", ["internet", "wireless", "router", "password", "connect"]],
  ["Password", "Technology", ["login", "secret", "account", "characters", "access"]],
  ["Email", "Technology", ["message", "inbox", "send", "address", "electronic"]],
  ["WhatsApp", "Technology", ["message", "chat", "phone", "status", "green"]],
  ["Google", "Technology", ["search", "internet", "website", "browser", "engine"]],
  ["Robot", "Technology", ["machine", "automatic", "human", "metal", "programmed"]],
  ["Drone", "Technology", ["fly", "camera", "remote", "air", "pilot"]],
  ["Printer", "Technology", ["paper", "ink", "computer", "print", "document"]],
  ["Charger", "Technology", ["battery", "phone", "cable", "power", "plug"]],
  ["Battery", "Technology", ["power", "charge", "energy", "positive", "negative"]],
  ["Keyboard", "Technology", ["keys", "type", "computer", "letters", "spacebar"]],
  ["Mouse", "Technology", ["computer", "click", "cursor", "scroll", "device"]],
  ["Screenshot", "Technology", ["screen", "picture", "capture", "phone", "image"]],
  ["Emoji", "Technology", ["face", "symbol", "message", "smiley", "reaction"]],
  ["Hashtag", "Technology", ["symbol", "social media", "trend", "number sign", "post"]],
  ["Online Shopping", "Technology", ["internet", "buy", "delivery", "cart", "website"]],
  ["Social Media", "Technology", ["online", "posts", "followers", "apps", "share"]],

  ["Load Shedding", "South Africa", ["Eskom", "electricity", "power", "outage", "lights"]],
  ["Springboks", "South Africa", ["rugby", "green", "gold", "national", "team"]],
  ["Bafana Bafana", "South Africa", ["football", "soccer", "national", "team", "yellow"]],
  ["Proteas", "South Africa", ["cricket", "national", "team", "South Africa", "flower"]],
  ["Nelson Mandela", "South Africa", ["president", "prison", "apartheid", "Madiba", "Robben Island"]],
  ["Table Mountain", "South Africa", ["Cape Town", "flat", "cable car", "landmark", "peak"]],
  ["Kruger National Park", "South Africa", ["animals", "safari", "wildlife", "game reserve", "Mpumalanga"]],
  ["Johannesburg", "South Africa", ["Gauteng", "city", "Joburg", "gold", "Sandton"]],
  ["Cape Town", "South Africa", ["Western Cape", "Table Mountain", "city", "ocean", "Mother City"]],
  ["Durban", "South Africa", ["KwaZulu-Natal", "beach", "city", "warm", "Indian Ocean"]],
  ["Soweto", "South Africa", ["Johannesburg", "township", "Orlando", "Vilakazi Street", "Gauteng"]],
  ["Mzansi", "South Africa", ["South Africa", "country", "home", "nickname", "nation"]],
  ["Rand", "South Africa", ["money", "currency", "South Africa", "R", "coins"]],
  ["Minibus Taxi", "South Africa", ["transport", "driver", "rank", "fare", "commute"]],
  ["Gautrain", "South Africa", ["train", "Gauteng", "Johannesburg", "Pretoria", "rapid"]],
  ["Vuvuzela", "South Africa", ["horn", "football", "loud", "blow", "stadium"]],
  ["Pap", "South African Food", ["maize", "porridge", "stiff", "mealie meal", "food"]],
  ["Chakalaka", "South African Food", ["spicy", "relish", "vegetables", "beans", "pap"]],
  ["Biltong", "South African Food", ["dried", "meat", "beef", "snack", "spice"]],
  ["Koeksister", "South African Food", ["sweet", "syrup", "twisted", "fried", "dessert"]],
  ["Rooibos", "South African Food", ["tea", "red", "drink", "herbal", "Cederberg"]],
  ["Vetkoek", "South African Food", ["fried", "dough", "bread", "mince", "fat cake"]],
  ["Kota", "South African Food", ["bread", "chips", "township", "filling", "quarter"]],
  ["Shisanyama", "South African Food", ["meat", "braai", "fire", "township", "grill"]],
  ["Ubuntu", "South Africa", ["humanity", "people", "together", "community", "African"]],
  ["Heritage Day", "South Africa", ["September", "culture", "tradition", "holiday", "braai"]],
  ["Freedom Day", "South Africa", ["April", "democracy", "election", "holiday", "1994"]],
  ["Lobola", "South Africa", ["marriage", "bride", "cattle", "family", "payment"]],
  ["Matric", "South Africa", ["Grade 12", "school", "exams", "final year", "certificate"]],
  ["Stokvel", "South Africa", ["money", "save", "group", "monthly", "contribution"]],
] as const;
