import { TABOO_BANK as PREVIOUS_TABOO_BANK, type TabooCard } from "./taboo-bank-v3";

// Version 4 expands the curated bank without replacing the existing cards.
// Every prohibited list blocks the five clues players are most likely to use.
export const TABOO_V4_ADDITIONS: readonly TabooCard[] = [
  ["Vacuum Cleaner", "Home & Chores", ["carpet", "suck", "dust", "floor", "clean"]],
  ["Dishwasher", "Home & Chores", ["plates", "kitchen", "soap", "machine", "clean"]],
  ["Iron", "Home & Chores", ["clothes", "hot", "wrinkles", "steam", "press"]],
  ["Curtains", "Home & Chores", ["window", "open", "close", "fabric", "blinds"]],
  ["Mattress", "Home & Chores", ["bed", "sleep", "soft", "springs", "pillow"]],
  ["Doorbell", "Home & Chores", ["ring", "door", "visitor", "press", "house"]],
  ["Dustbin", "Home & Chores", ["rubbish", "trash", "waste", "lid", "throw"]],
  ["Mop", "Home & Chores", ["floor", "water", "clean", "bucket", "wet"]],
  ["Light Bulb", "Home & Chores", ["lamp", "bright", "electricity", "switch", "glow"]],
  ["Extension Cord", "Home & Chores", ["plug", "cable", "socket", "power", "long"]],

  ["Hoodie", "Clothing & Fashion", ["jacket", "hood", "sweatshirt", "wear", "head"]],
  ["High Heels", "Clothing & Fashion", ["shoes", "tall", "women", "feet", "walk"]],
  ["Socks", "Clothing & Fashion", ["feet", "shoes", "pair", "wear", "ankle"]],
  ["Belt", "Clothing & Fashion", ["waist", "trousers", "buckle", "tighten", "leather"]],
  ["Handbag", "Clothing & Fashion", ["purse", "woman", "carry", "shoulder", "accessory"]],
  ["Uniform", "Clothing & Fashion", ["school", "work", "same", "clothes", "wear"]],
  ["Pyjamas", "Clothing & Fashion", ["sleep", "bed", "night", "clothes", "wear"]],
  ["Wedding Dress", "Clothing & Fashion", ["bride", "white", "marriage", "gown", "ceremony"]],
  ["Necklace", "Clothing & Fashion", ["jewellery", "neck", "chain", "wear", "pendant"]],
  ["Cap", "Clothing & Fashion", ["hat", "head", "peak", "wear", "baseball"]],

  ["Avocado", "Food & Drink", ["green", "fruit", "toast", "guacamole", "pit"]],
  ["Pancake", "Food & Drink", ["flat", "breakfast", "syrup", "batter", "flip"]],
  ["Cereal", "Food & Drink", ["breakfast", "milk", "bowl", "flakes", "spoon"]],
  ["Sushi", "Food & Drink", ["Japan", "rice", "fish", "raw", "roll"]],
  ["Curry", "Food & Drink", ["spicy", "sauce", "India", "rice", "cook"]],
  ["Steak", "Food & Drink", ["beef", "meat", "grill", "rare", "cow"]],
  ["Smoothie", "Food & Drink", ["fruit", "drink", "blender", "healthy", "thick"]],
  ["Peanut Butter", "Food & Drink", ["spread", "bread", "nuts", "sandwich", "sticky"]],
  ["Hot Dog", "Food & Drink", ["sausage", "bun", "mustard", "ketchup", "food"]],
  ["Cupcake", "Food & Drink", ["small", "cake", "icing", "bake", "sweet"]],

  ["Headache", "Body & Health", ["head", "pain", "medicine", "migraine", "hurt"]],
  ["Toothache", "Body & Health", ["tooth", "pain", "dentist", "mouth", "cavity"]],
  ["Fever", "Body & Health", ["temperature", "hot", "sick", "thermometer", "ill"]],
  ["Allergy", "Body & Health", ["sneeze", "reaction", "pollen", "itch", "food"]],
  ["Bandage", "Body & Health", ["wound", "cut", "cover", "injury", "plaster"]],
  ["Ambulance", "Body & Health", ["emergency", "hospital", "siren", "paramedic", "vehicle"]],
  ["Crutches", "Body & Health", ["walk", "leg", "injury", "support", "armpit"]],
  ["Blood Pressure", "Body & Health", ["heart", "high", "low", "cuff", "doctor"]],
  ["Vitamins", "Body & Health", ["health", "supplements", "pills", "nutrients", "body"]],
  ["Sunburn", "Body & Health", ["sun", "skin", "red", "pain", "cream"]],

  ["Salary", "Work & Money", ["money", "job", "pay", "monthly", "wage"]],
  ["Job Interview", "Work & Money", ["questions", "employer", "hire", "CV", "position"]],
  ["CV", "Work & Money", ["résumé", "jobs", "experience", "skills", "apply"]],
  ["Promotion", "Work & Money", ["job", "higher", "position", "raise", "work"]],
  ["Overtime", "Work & Money", ["extra", "hours", "work", "late", "pay"]],
  ["Deadline", "Work & Money", ["due", "time", "finish", "date", "late"]],
  ["Meeting", "Work & Money", ["office", "people", "discuss", "room", "agenda"]],
  ["Office", "Work & Money", ["work", "desk", "computer", "building", "job"]],
  ["Retirement", "Work & Money", ["stop", "working", "old", "pension", "age"]],
  ["Budget", "Work & Money", ["money", "spend", "save", "plan", "expenses"]],

  ["Customs", "Travel", ["airport", "border", "declare", "bags", "officer"]],
  ["Visa", "Travel", ["passport", "country", "travel", "embassy", "permit"]],
  ["Jet Lag", "Travel", ["tired", "flight", "time zone", "sleep", "travel"]],
  ["Departure", "Travel", ["leave", "airport", "flight", "time", "gate"]],
  ["Arrival", "Travel", ["reach", "airport", "land", "destination", "flight"]],
  ["Tour Guide", "Travel", ["visitor", "show", "city", "group", "information"]],
  ["Campsite", "Travel", ["tent", "outdoors", "sleep", "fire", "camp"]],
  ["Car Rental", "Travel", ["hire", "vehicle", "drive", "airport", "return"]],
  ["Travel Insurance", "Travel", ["trip", "cover", "claim", "medical", "cancel"]],
  ["Souvenir", "Travel", ["gift", "holiday", "remember", "buy", "tourist"]],

  ["QR Code", "Technology", ["scan", "square", "phone", "camera", "link"]],
  ["Video Call", "Technology", ["camera", "online", "face", "meeting", "talk"]],
  ["Voice Note", "Technology", ["record", "audio", "message", "WhatsApp", "send"]],
  ["Bluetooth", "Technology", ["wireless", "connect", "phone", "speaker", "pair"]],
  ["Airplane Mode", "Technology", ["phone", "flight", "signal", "off", "network"]],
  ["Search Engine", "Technology", ["Google", "internet", "find", "web", "query"]],
  ["Username", "Technology", ["account", "login", "name", "profile", "password"]],
  ["Notification", "Technology", ["alert", "phone", "message", "sound", "pop-up"]],
  ["Livestream", "Technology", ["live", "video", "internet", "watch", "broadcast"]],
  ["Streaming", "Technology", ["watch", "online", "video", "music", "internet"]],

  ["Movie Trailer", "Entertainment", ["film", "preview", "cinema", "coming", "clip"]],
  ["Red Carpet", "Entertainment", ["celebrity", "event", "photos", "premiere", "walk"]],
  ["Talent Show", "Entertainment", ["sing", "dance", "judges", "perform", "contest"]],
  ["Game Show", "Entertainment", ["television", "contestants", "questions", "prize", "host"]],
  ["Music Festival", "Entertainment", ["concert", "artists", "stage", "crowd", "songs"]],
  ["Autograph", "Entertainment", ["signature", "celebrity", "fan", "sign", "famous"]],
  ["Fan Club", "Entertainment", ["supporters", "celebrity", "group", "follow", "members"]],
  ["Spoiler", "Entertainment", ["ending", "movie", "reveal", "story", "ruin"]],
  ["Binge-Watch", "Entertainment", ["episodes", "series", "Netflix", "all", "watch"]],
  ["Meme", "Entertainment", ["internet", "funny", "picture", "viral", "caption"]],

  ["Gravity", "Science", ["fall", "Earth", "pull", "force", "down"]],
  ["Magnet", "Science", ["metal", "attract", "north", "south", "stick"]],
  ["Solar System", "Science", ["Sun", "planets", "space", "Earth", "orbit"]],
  ["Planet", "Science", ["space", "Earth", "orbit", "Sun", "world"]],
  ["Telescope", "Science", ["space", "stars", "look", "lens", "astronomy"]],
  ["Microscope", "Science", ["small", "cells", "lens", "science", "magnify"]],
  ["Dinosaur", "Science", ["extinct", "prehistoric", "fossil", "reptile", "Jurassic"]],
  ["Fossil", "Science", ["old", "bones", "rock", "dinosaur", "remains"]],
  ["Electricity", "Science", ["power", "current", "wires", "energy", "shock"]],
  ["Experiment", "Science", ["test", "laboratory", "science", "results", "hypothesis"]],

  ["Hurricane", "Nature", ["storm", "wind", "ocean", "damage", "cyclone"]],
  ["Flood", "Nature", ["water", "rain", "overflow", "houses", "river"]],
  ["Drought", "Nature", ["dry", "water", "rain", "crops", "long"]],
  ["Glacier", "Nature", ["ice", "cold", "mountain", "melt", "large"]],
  ["Cave", "Nature", ["dark", "rock", "underground", "bat", "hole"]],
  ["River", "Nature", ["water", "flow", "bank", "sea", "stream"]],
  ["Lake", "Nature", ["water", "land", "swim", "inland", "shore"]],
  ["Jungle", "Nature", ["trees", "animals", "forest", "tropical", "wild"]],
  ["Coral Reef", "Nature", ["ocean", "fish", "colourful", "underwater", "diving"]],
  ["Eclipse", "Nature", ["Sun", "Moon", "dark", "block", "sky"]],

  ["Roommate", "Relationships", ["live", "house", "share", "rent", "person"]],
  ["Ex-Partner", "Relationships", ["former", "relationship", "breakup", "dated", "past"]],
  ["Crush", "Relationships", ["like", "romantic", "secret", "person", "feelings"]],
  ["Blind Date", "Relationships", ["meet", "stranger", "romantic", "restaurant", "set up"]],
  ["Long-Distance Relationship", "Relationships", ["far", "couple", "travel", "video call", "apart"]],
  ["Engagement", "Relationships", ["ring", "marry", "proposal", "couple", "wedding"]],
  ["Honeymoon", "Relationships", ["wedding", "holiday", "married", "couple", "trip"]],
  ["Gossip", "Relationships", ["rumour", "talk", "people", "secret", "spread"]],
  ["Compliment", "Relationships", ["nice", "praise", "say", "flatter", "kind"]],
  ["Awkward Silence", "Relationships", ["quiet", "uncomfortable", "talk", "pause", "nothing"]],

  ["Cape of Good Hope", "South Africa", ["Cape Town", "ocean", "point", "peninsula", "Africa"]],
  ["Drakensberg", "South Africa", ["mountains", "KwaZulu-Natal", "hiking", "range", "peaks"]],
  ["Gold Reef City", "South Africa", ["Johannesburg", "theme park", "rides", "casino", "gold"]],
  ["Sun City", "South Africa", ["resort", "North West", "holiday", "casino", "Valley of Waves"]],
  ["Zulu", "South African Languages", ["language", "KwaZulu-Natal", "people", "isiZulu", "South Africa"]],
  ["Xhosa", "South African Languages", ["language", "clicks", "Eastern Cape", "isiXhosa", "South Africa"]],
  ["Tsonga", "South African Languages", ["language", "XiTsonga", "Limpopo", "people", "South Africa"]],
  ["Sesotho", "South African Languages", ["language", "Free State", "Basotho", "Lesotho", "South Africa"]],
  ["Afrikaans", "South African Languages", ["language", "Dutch", "speak", "South Africa", "Cape"]],
  ["Cape Town Minstrels", "South Africa", ["colourful", "parade", "music", "January", "Kaapse Klopse"]],

  ["Safari", "Africa", ["animals", "game drive", "Africa", "wildlife", "jeep"]],
  ["Sahara", "Africa", ["desert", "sand", "Africa", "hot", "largest"]],
  ["Nile River", "Africa", ["Egypt", "water", "Africa", "longest", "flow"]],
  ["Kilimanjaro", "Africa", ["mountain", "Tanzania", "Africa", "highest", "climb"]],
  ["Maasai", "Africa", ["Kenya", "Tanzania", "people", "culture", "red"]],
  ["Afrobeat", "Africa", ["music", "Nigeria", "rhythm", "Fela Kuti", "genre"]],
  ["Ankara Fabric", "Africa", ["cloth", "colourful", "print", "fashion", "wax"]],
  ["Jollof Rice", "Africa", ["West Africa", "tomato", "Nigeria", "Ghana", "dish"]],
  ["Fufu", "Africa", ["food", "West Africa", "dough", "swallow", "cassava"]],
  ["African Union", "Africa", ["countries", "organisation", "continent", "Addis Ababa", "leaders"]],

  ["Hangover", "Adult Life", ["alcohol", "drunk", "morning", "headache", "drink"]],
  ["Rent", "Adult Life", ["money", "monthly", "house", "landlord", "pay"]],
  ["Landlord", "Adult Life", ["rent", "owner", "house", "tenant", "property"]],
  ["Tenant", "Adult Life", ["rent", "landlord", "live", "property", "lease"]],
  ["Deposit", "Adult Life", ["money", "pay", "rent", "bank", "return"]],
  ["Grocery List", "Adult Life", ["shopping", "food", "write", "supermarket", "items"]],
  ["Alarm Clock", "Adult Life", ["wake", "morning", "ring", "time", "sleep"]],
  ["Traffic Fine", "Adult Life", ["police", "speed", "ticket", "car", "pay"]],
  ["Insurance", "Adult Life", ["cover", "policy", "claim", "risk", "pay"]],
  ["Mortgage", "Adult Life", ["house", "bank", "loan", "monthly", "interest"]],

  ["Procrastinate", "Actions", ["delay", "later", "avoid", "task", "time"]],
  ["Eavesdrop", "Actions", ["listen", "secretly", "conversation", "hear", "private"]],
  ["Daydream", "Actions", ["imagine", "mind", "awake", "fantasy", "think"]],
  ["Panic", "Actions", ["fear", "sudden", "calm", "worry", "emergency"]],
  ["Blush", "Actions", ["face", "red", "embarrassed", "cheeks", "shy"]],
  ["Forgive", "Actions", ["sorry", "mistake", "anger", "accept", "apology"]],
  ["Encourage", "Actions", ["support", "motivate", "confidence", "help", "positive"]],
  ["Interrupt", "Actions", ["stop", "talking", "speak", "middle", "cut off"]],
  ["Negotiate", "Actions", ["deal", "agree", "discuss", "price", "compromise"]],
  ["Concentrate", "Actions", ["focus", "attention", "think", "task", "distracted"]],
];

export const TABOO_BANK: readonly TabooCard[] = [
  ...PREVIOUS_TABOO_BANK,
  ...TABOO_V4_ADDITIONS,
];
