import { TABOO_BANK as PREVIOUS_TABOO_BANK, type TabooCard } from "./taboo-bank";

// Version 3 keeps 55 strong cards from the previous bank and replaces the
// remaining 165. The replacements focus on the five clues players are most
// likely to say first, rather than loosely related dictionary words.
export const TABOO_V3_REPLACEMENTS: readonly TabooCard[] = [
  ["Dentist", "People & Jobs", ["teeth", "mouth", "doctor", "drill", "cavity"]],
  ["Barber", "People & Jobs", ["hair", "cut", "clippers", "salon", "shave"]],
  ["Waiter", "People & Jobs", ["restaurant", "food", "serve", "table", "tip"]],
  ["Lawyer", "People & Jobs", ["court", "law", "judge", "case", "client"]],
  ["Cashier", "People & Jobs", ["money", "till", "shop", "pay", "receipt"]],
  ["Photographer", "People & Jobs", ["camera", "pictures", "photos", "lens", "shoot"]],
  ["Plumber", "People & Jobs", ["pipes", "water", "toilet", "leak", "repair"]],
  ["Electrician", "People & Jobs", ["wires", "power", "electricity", "plug", "repair"]],
  ["Journalist", "People & Jobs", ["news", "report", "story", "newspaper", "interview"]],
  ["Actor", "People & Jobs", ["movie", "play", "character", "stage", "perform"]],
  ["DJ", "People & Jobs", ["music", "songs", "club", "mix", "turntable"]],
  ["Referee", "People & Jobs", ["game", "whistle", "rules", "sport", "official"]],
  ["Architect", "People & Jobs", ["building", "design", "plans", "draw", "house"]],
  ["Security Guard", "People & Jobs", ["protect", "uniform", "gate", "watch", "safety"]],
  ["Delivery Driver", "People & Jobs", ["package", "door", "van", "order", "bring"]],

  ["Hospital", "Places", ["doctor", "nurse", "patient", "sick", "medicine"]],
  ["Airport", "Places", ["plane", "flight", "travel", "passport", "terminal"]],
  ["Library", "Places", ["books", "read", "quiet", "borrow", "shelves"]],
  ["Restaurant", "Places", ["food", "eat", "waiter", "menu", "table"]],
  ["Cinema", "Places", ["movie", "screen", "popcorn", "film", "tickets"]],
  ["Beach", "Places", ["sand", "sea", "ocean", "swim", "waves"]],
  ["Museum", "Places", ["history", "art", "exhibits", "old", "visit"]],
  ["Stadium", "Places", ["sport", "crowd", "seats", "field", "match"]],
  ["Supermarket", "Places", ["shop", "groceries", "food", "trolley", "aisles"]],
  ["Pharmacy", "Places", ["medicine", "pills", "chemist", "prescription", "health"]],
  ["Gym", "Places", ["exercise", "weights", "fitness", "workout", "muscles"]],
  ["Church", "Places", ["pray", "religion", "Sunday", "pastor", "worship"]],
  ["Hotel", "Places", ["room", "sleep", "holiday", "reception", "guest"]],
  ["Prison", "Places", ["jail", "criminal", "bars", "cell", "sentence"]],
  ["Playground", "Places", ["children", "swings", "slide", "park", "play"]],

  ["Lion", "Animals", ["king", "jungle", "roar", "mane", "cat"]],
  ["Elephant", "Animals", ["trunk", "tusks", "grey", "large", "animal"]],
  ["Giraffe", "Animals", ["tall", "neck", "spots", "Africa", "animal"]],
  ["Penguin", "Animals", ["black", "white", "ice", "bird", "waddle"]],
  ["Dolphin", "Animals", ["ocean", "swim", "intelligent", "fin", "mammal"]],
  ["Shark", "Animals", ["ocean", "teeth", "fin", "dangerous", "fish"]],
  ["Crocodile", "Animals", ["teeth", "river", "reptile", "water", "alligator"]],
  ["Monkey", "Animals", ["banana", "tree", "ape", "climb", "tail"]],
  ["Kangaroo", "Animals", ["Australia", "jump", "pouch", "baby", "hop"]],
  ["Owl", "Animals", ["night", "bird", "eyes", "hoot", "wise"]],
  ["Snake", "Animals", ["slither", "bite", "venom", "reptile", "long"]],
  ["Spider", "Animals", ["eight", "legs", "web", "insect", "bite"]],
  ["Butterfly", "Animals", ["wings", "colourful", "caterpillar", "fly", "insect"]],
  ["Frog", "Animals", ["jump", "green", "pond", "croak", "tadpole"]],
  ["Zebra", "Animals", ["stripes", "black", "white", "horse", "Africa"]],

  ["Rainbow", "Nature & Weather", ["colours", "rain", "sky", "arc", "sun"]],
  ["Thunder", "Nature & Weather", ["storm", "lightning", "loud", "sky", "sound"]],
  ["Lightning", "Nature & Weather", ["thunder", "flash", "storm", "sky", "electric"]],
  ["Tornado", "Nature & Weather", ["wind", "funnel", "storm", "spin", "destroy"]],
  ["Snow", "Nature & Weather", ["white", "cold", "winter", "ice", "flakes"]],
  ["Desert", "Nature & Weather", ["sand", "hot", "dry", "camel", "water"]],
  ["Volcano", "Nature & Weather", ["lava", "eruption", "mountain", "hot", "ash"]],
  ["Earthquake", "Nature & Weather", ["ground", "shake", "buildings", "magnitude", "tremor"]],
  ["Waterfall", "Nature & Weather", ["water", "river", "drop", "cliff", "flow"]],
  ["Island", "Nature & Weather", ["water", "ocean", "land", "beach", "surrounded"]],
  ["Forest", "Nature & Weather", ["trees", "woods", "animals", "green", "nature"]],
  ["Moon", "Nature & Weather", ["night", "sky", "space", "round", "Earth"]],
  ["Sunrise", "Nature & Weather", ["morning", "sun", "east", "dawn", "light"]],
  ["Shadow", "Nature & Weather", ["light", "dark", "shape", "sun", "follow"]],
  ["Cloud", "Nature & Weather", ["sky", "white", "rain", "weather", "fluffy"]],

  ["Homework", "School & Technology", ["school", "teacher", "study", "assignment", "home"]],
  ["Calculator", "School & Technology", ["maths", "numbers", "add", "buttons", "calculate"]],
  ["Dictionary", "School & Technology", ["words", "meaning", "book", "definition", "alphabet"]],
  ["Exam", "School & Technology", ["test", "study", "questions", "school", "marks"]],
  ["Graduation", "School & Technology", ["degree", "university", "cap", "gown", "ceremony"]],
  ["Laptop", "School & Technology", ["computer", "screen", "keyboard", "portable", "work"]],
  ["Internet", "School & Technology", ["online", "web", "Wi-Fi", "browser", "connect"]],
  ["Password", "School & Technology", ["login", "secret", "account", "characters", "access"]],
  ["Email", "School & Technology", ["message", "send", "inbox", "address", "online"]],
  ["Screenshot", "School & Technology", ["screen", "picture", "capture", "phone", "image"]],
  ["Keyboard", "School & Technology", ["type", "computer", "keys", "letters", "spacebar"]],
  ["Charger", "School & Technology", ["battery", "phone", "power", "cable", "plug"]],
  ["Wi-Fi", "School & Technology", ["internet", "wireless", "router", "password", "connect"]],
  ["Robot", "School & Technology", ["machine", "human", "automatic", "metal", "program"]],
  ["Artificial Intelligence", "School & Technology", ["AI", "computer", "ChatGPT", "machine", "smart"]],

  ["Concert", "Entertainment", ["music", "live", "singer", "stage", "crowd"]],
  ["Podcast", "Entertainment", ["listen", "audio", "episode", "host", "talk"]],
  ["Karaoke", "Entertainment", ["sing", "microphone", "lyrics", "music", "bar"]],
  ["Cartoon", "Entertainment", ["animated", "children", "drawings", "television", "character"]],
  ["Comedy", "Entertainment", ["funny", "laugh", "jokes", "stand-up", "humour"]],
  ["Horror Movie", "Entertainment", ["scary", "film", "ghost", "scream", "fear"]],
  ["Reality Show", "Entertainment", ["television", "real", "contestants", "drama", "camera"]],
  ["Video Game", "Entertainment", ["play", "console", "controller", "screen", "gaming"]],
  ["Board Game", "Entertainment", ["dice", "pieces", "table", "players", "rules"]],
  ["Magic Trick", "Entertainment", ["magician", "illusion", "cards", "disappear", "rabbit"]],
  ["Celebrity", "Entertainment", ["famous", "star", "actor", "singer", "public"]],
  ["Superhero", "Entertainment", ["powers", "cape", "save", "villain", "comic"]],
  ["Documentary", "Entertainment", ["facts", "film", "real", "educational", "nature"]],
  ["Playlist", "Entertainment", ["songs", "music", "list", "Spotify", "listen"]],
  ["Dance Challenge", "Entertainment", ["TikTok", "moves", "music", "trend", "video"]],

  ["Football", "Sports", ["ball", "goal", "kick", "soccer", "team"]],
  ["Basketball", "Sports", ["ball", "hoop", "dribble", "court", "shoot"]],
  ["Rugby", "Sports", ["ball", "tackle", "scrum", "try", "team"]],
  ["Cricket", "Sports", ["bat", "ball", "wicket", "bowler", "runs"]],
  ["Tennis", "Sports", ["racket", "ball", "court", "net", "serve"]],
  ["Swimming", "Sports", ["water", "pool", "stroke", "race", "swim"]],
  ["Boxing", "Sports", ["fight", "gloves", "ring", "punch", "round"]],
  ["Marathon", "Sports", ["run", "race", "long", "kilometres", "runner"]],
  ["Golf", "Sports", ["club", "ball", "hole", "course", "swing"]],
  ["Cycling", "Sports", ["bicycle", "ride", "pedal", "helmet", "race"]],
  ["Gymnastics", "Sports", ["flip", "balance", "floor", "flexible", "routine"]],
  ["Wrestling", "Sports", ["fight", "ring", "pin", "grapple", "opponent"]],
  ["Skateboard", "Sports", ["board", "wheels", "trick", "ride", "ramp"]],
  ["Penalty", "Sports", ["foul", "kick", "referee", "punishment", "goal"]],
  ["Trophy", "Sports", ["winner", "cup", "prize", "award", "champion"]],

  ["Whisper", "Actions & Feelings", ["quiet", "speak", "soft", "secret", "voice"]],
  ["Sneeze", "Actions & Feelings", ["nose", "achoo", "tissue", "cold", "allergy"]],
  ["Laugh", "Actions & Feelings", ["funny", "smile", "joke", "sound", "happy"]],
  ["Cry", "Actions & Feelings", ["tears", "sad", "eyes", "upset", "weep"]],
  ["Yawn", "Actions & Feelings", ["tired", "mouth", "sleep", "open", "bored"]],
  ["Hug", "Actions & Feelings", ["arms", "embrace", "love", "hold", "person"]],
  ["Jealous", "Actions & Feelings", ["envy", "want", "possessive", "relationship", "green"]],
  ["Embarrassed", "Actions & Feelings", ["ashamed", "red", "awkward", "mistake", "shy"]],
  ["Confused", "Actions & Feelings", ["understand", "lost", "puzzled", "unsure", "question"]],
  ["Excited", "Actions & Feelings", ["happy", "eager", "energy", "cannot wait", "thrilled"]],
  ["Bored", "Actions & Feelings", ["nothing", "tired", "uninterested", "dull", "yawn"]],
  ["Apologise", "Actions & Feelings", ["sorry", "forgive", "mistake", "regret", "excuse"]],
  ["Celebrate", "Actions & Feelings", ["party", "win", "happy", "occasion", "cheer"]],
  ["Complain", "Actions & Feelings", ["problem", "unhappy", "service", "moan", "manager"]],
  ["Promise", "Actions & Feelings", ["keep", "word", "swear", "commit", "break"]],

  ["Load Shedding", "South Africa", ["Eskom", "electricity", "power", "outage", "lights"]],
  ["Springboks", "South Africa", ["rugby", "green", "gold", "national", "team"]],
  ["Bafana Bafana", "South Africa", ["football", "national", "team", "soccer", "yellow"]],
  ["Amapiano", "South Africa", ["music", "piano", "dance", "South Africa", "log drum"]],
  ["Traffic Robot", "South African English", ["traffic light", "road", "red", "green", "intersection"]],
  ["Tekkies", "South African English", ["shoes", "sneakers", "feet", "trainers", "wear"]],
  ["Bakkie", "South African English", ["vehicle", "truck", "load", "drive", "pickup"]],
  ["Spaza Shop", "South Africa", ["township", "small", "store", "buy", "groceries"]],
  ["Shebeen", "South Africa", ["tavern", "drink", "township", "bar", "alcohol"]],
  ["Gogo", "South Africa", ["grandmother", "old", "family", "woman", "granny"]],
  ["Mzansi Magic", "South Africa", ["television", "channel", "DStv", "shows", "drama"]],
  ["Union Buildings", "South Africa", ["Pretoria", "government", "president", "landmark", "office"]],
  ["Robben Island", "South Africa", ["Mandela", "prison", "Cape Town", "ferry", "history"]],
  ["Blyde River Canyon", "South Africa", ["Mpumalanga", "mountains", "view", "nature", "canyon"]],
  ["Comrades Marathon", "South Africa", ["run", "Durban", "Pietermaritzburg", "race", "ultra"]],

  ["Passport", "Travel", ["travel", "country", "document", "airport", "stamp"]],
  ["Suitcase", "Travel", ["clothes", "travel", "pack", "luggage", "trip"]],
  ["Map", "Travel", ["directions", "location", "road", "navigate", "country"]],
  ["Traffic Jam", "Travel", ["cars", "road", "slow", "stuck", "rush hour"]],
  ["Seatbelt", "Travel", ["car", "safety", "strap", "wear", "buckle"]],
  ["Petrol Station", "Travel", ["fuel", "car", "gas", "fill", "pump"]],
  ["Taxi", "Travel", ["driver", "ride", "fare", "transport", "car"]],
  ["Train", "Travel", ["railway", "station", "tracks", "carriage", "transport"]],
  ["Cruise Ship", "Travel", ["ocean", "boat", "holiday", "passengers", "travel"]],
  ["Tourist", "Travel", ["visitor", "travel", "camera", "holiday", "sightseeing"]],
  ["Road Trip", "Travel", ["car", "drive", "long", "friends", "journey"]],
  ["Boarding Pass", "Travel", ["flight", "plane", "airport", "seat", "ticket"]],
  ["Window Seat", "Travel", ["plane", "view", "aisle", "sit", "flight"]],
  ["Destination", "Travel", ["place", "travel", "going", "arrival", "journey"]],
  ["Directions", "Travel", ["left", "right", "map", "where", "route"]],

  ["Birthday", "Events & Relationships", ["cake", "candles", "party", "age", "celebrate"]],
  ["Wedding", "Events & Relationships", ["bride", "groom", "marriage", "ring", "ceremony"]],
  ["Funeral", "Events & Relationships", ["death", "bury", "coffin", "sad", "mourning"]],
  ["Baby Shower", "Events & Relationships", ["pregnant", "gifts", "mother", "baby", "party"]],
  ["Anniversary", "Events & Relationships", ["year", "couple", "marriage", "date", "celebrate"]],
  ["First Date", "Events & Relationships", ["romantic", "meet", "restaurant", "couple", "nervous"]],
  ["Breakup", "Events & Relationships", ["relationship", "end", "couple", "separate", "heartbroken"]],
  ["Best Friend", "Events & Relationships", ["close", "person", "trust", "friendship", "together"]],
  ["Neighbour", "Events & Relationships", ["next door", "house", "live", "street", "person"]],
  ["Family Reunion", "Events & Relationships", ["relatives", "gather", "home", "together", "meet"]],
  ["Surprise Party", "Events & Relationships", ["secret", "birthday", "hide", "unexpected", "celebrate"]],
  ["Invitation", "Events & Relationships", ["event", "come", "card", "guest", "RSVP"]],
  ["Gift", "Events & Relationships", ["present", "give", "birthday", "wrap", "surprise"]],
  ["Argument", "Events & Relationships", ["fight", "disagree", "shout", "angry", "couple"]],
  ["Secret", "Events & Relationships", ["tell", "private", "hide", "know", "share"]],
] as const;

export const TABOO_BANK: readonly TabooCard[] = [
  ...PREVIOUS_TABOO_BANK.slice(0, 55),
  ...TABOO_V3_REPLACEMENTS,
];
