import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
export const rooms=sqliteTable("rooms",{id:text("id").primaryKey(),code:text("code").notNull().unique(),hostTokenHash:text("host_token_hash").notNull(),state:text("state").notNull(),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),expiresAt:text("expires_at").notNull()});
export const gameContent=sqliteTable("game_content",{id:integer("id").primaryKey({autoIncrement:true}),gameType:text("game_type").notNull(),prompt:text("prompt").notNull(),answer:text("answer"),category:text("category"),metadata:text("metadata").notNull().default("{}"),isActive:integer("is_active",{mode:"boolean"}).notNull().default(true),ownerRoomId:text("owner_room_id"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)},t=>[uniqueIndex("game_content_unique").on(t.gameType,t.prompt,t.ownerRoomId),index("game_content_type_active_owner_idx").on(t.gameType,t.isActive,t.ownerRoomId)]);
export const roomContentSettings=sqliteTable("room_content_settings",{id:integer("id").primaryKey({autoIncrement:true}),roomId:text("room_id").notNull(),contentId:integer("content_id").notNull(),enabled:integer("enabled",{mode:"boolean"}).notNull().default(true)},t=>[index("room_content_settings_room_id_idx").on(t.roomId)]);
export const eventTeams=sqliteTable("event_teams",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),normalizedName:text("normalized_name").notNull(),totalScore:integer("total_score").notNull().default(0),matchesPlayed:integer("matches_played").notNull().default(0),gamesWon:integer("games_won").notNull().default(0),correctAnswers:integer("correct_answers").notNull().default(0),answersPlayed:integer("answers_played").notNull().default(0),updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`)},t=>[uniqueIndex("event_teams_name_unique").on(t.normalizedName)]);
export const gameSessions=sqliteTable("game_sessions",{id:text("id").primaryKey(),roomId:text("room_id").notNull(),gameType:text("game_type"),teamAName:text("team_a_name"),teamBName:text("team_b_name"),startedAt:text("started_at").notNull().default(sql`CURRENT_TIMESTAMP`),endedAt:text("ended_at"),finalState:text("final_state")},t=>[index("game_sessions_room_id_idx").on(t.roomId)]);
export const rounds=sqliteTable("rounds",{id:text("id").primaryKey(),sessionId:text("session_id").notNull(),gameType:text("game_type").notNull(),team:text("team").notNull(),teamName:text("team_name"),contentId:integer("content_id"),prompt:text("prompt"),answer:text("answer"),detail:text("detail"),result:text("result"),points:integer("points").notNull().default(0),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)},t=>[index("rounds_session_created_idx").on(t.sessionId,t.createdAt)]);
export const contentUsage=sqliteTable("content_usage",{id:integer("id").primaryKey({autoIncrement:true}),roomId:text("room_id").notNull(),sessionId:text("session_id").notNull(),contentId:integer("content_id").notNull(),gameType:text("game_type").notNull(),teamName:text("team_name").notNull(),result:text("result"),usedAt:text("used_at").notNull().default(sql`CURRENT_TIMESTAMP`)},t=>[uniqueIndex("content_usage_session_item_unique").on(t.sessionId,t.contentId),index("content_usage_room_game_id_idx").on(t.roomId,t.gameType,t.id)]);
